### ISSUE TITLE
Fieldset legend text can be clipped when using a custom or fallback font

### ISSUE THREAD

**Issue by stevesims** [alphagov/govuk-frontend#1239]
The SASS for `.govuk-fieldset__legend` has a line that sets `overflow: hidden`, as follows:
https://github.com/alphagov/govuk-frontend/blob/b52474c4c1c98c9886b48caafa3746bf7782859d/src/components/fieldset/_fieldset.scss#L25

From what I can tell the webkit bug this relates to was [this one](https://bugs.webkit.org/show_bug.cgi?id=35981) which was fixed over 6 years ago.

Having this in there can mean that if the NTA font isn't present, the bottom of legends can get chopped off for larger font sizes, and the descenders in Arial end up overflowing the element and thus hidden.

**Comment by nickcolley** [comment]
Hey @stevesims, thanks for letting us know about this.

I have reproduced this here:

https://govuk-frontend-issue-1239.glitch.me/

You can see the descenders from the 'g' in the title is clipped.

<img width="136" alt="screen shot 2019-03-05 at 17 48 05" src="https://user-images.githubusercontent.com/2445413/53825679-bd83e180-3f6e-11e9-8166-9efd81309724.png">

**Comment by nickcolley** [comment]
<img width="455" alt="screen shot 2019-03-05 at 17 53 15" src="https://user-images.githubusercontent.com/2445413/53826344-51a27880-3f70-11e9-8b17-dbfd298e693b.png">

You can see that with the regular headings that they also clip, but because they do not have this 'overflow: hidden' you will not notice it.

<img width="461" alt="screen shot 2019-03-05 at 17 54 30" src="https://user-images.githubusercontent.com/2445413/53826357-56ffc300-3f70-11e9-9de2-15c7631ee7d6.png">

I think this is likely because the [font scale](https://github.com/alphagov/govuk-frontend/blob/master/src/settings/_typography-responsive.scss#L67) has been designed with NTA only in mind.

We have a new version of the font that has a different baseline which might avoid this issue.

@dashouse might have some insight into what is the best thing to do here.

**Comment by nickcolley** [comment]
I've updated the title to make it focused on the problem as there may be a different solution to this issue, hope this is OK

**Comment by dashouse** [comment]
Good spot, we did a fair bit of checking between NTA and Arial but the legend specific styles were added a couple of months after that so didn't spot this.

The fact it's overflowing generally is ok, I believe it's because the line-height for the larger font sizes is actually smaller than the em-box of the font so they technically overlap even though the actual glyphs don't. This is to have a computed line height of 50px to lock it in the the baseline grid as well as feeling about right.

The newer cut of the font sits in the same position as Arial / Helvetica so we'll have to test this.

Do we know what versions of browsers would be affected by removing `overflow: hidden`?

**Comment by 36degrees** [comment]
The 'hack' was introduced in https://github.com/alphagov/govuk_elements/pull/484 in June 2017, so I don't _think_ it relates to the bug you reference given how old it is.

From reading that PR, I think it's a fix to allow hint text within legends to have margins.

As we [don't put hints or error messages within the legends any more](https://github.com/alphagov/govuk-frontend/pull/681) perhaps it's not be a problem any more, and the hack can be removed? We'd need to test it thoroughly in all of our supported browsers.

**Comment by stevesims** [comment]
I just read around a bit more on this.  I can't find much by googling about that's "current" (within the past 3 years).  The references on alphagov/govuk_elements#484 point towards a rejected PR alphagov/govuk_elements#76 which contains the comment:

> In Webkit, the bottom margin of a legend and the top margin of the next element don't overlap, which they should. This addresses that by discarding the top margin of the next element

This may well be the underlying issue that was attempted to be addressed.  (Again tho, I'm not sure whether this would still be an existant issue in WebKit/Blink based browsers - would need to experiment/test to find out.)

Given that spacing between elements in govuk-frontend primarily (with only a few exceptions) works through the use of `margin-bottom` it does feel that this would no longer be an issue.

**Comment by andymantell** [comment]
Just to say that I have observed this with the NTA font as well, it doesn't just seem to occur with Arial or other fallbacks. See demo here:

https://bush-monarch.glitch.me/

And screenshot of the above:

![image](https://user-images.githubusercontent.com/134642/63517384-ccdbf480-c4e6-11e9-8508-16696d5087da.png)

**Comment by nickcolley** [comment]
Note that your example Andy has overriden font (since it's not on a gov.uk domain), so the demonstration Glitch apps use a custom font.

Here's what happens if you don't use a custom font:

<img width="981" alt="font is not clipped" src="https://user-images.githubusercontent.com/2445413/64125289-5c17c080-cda1-11e9-9552-c423508ef9e6.png">
