### ISSUE TITLE
The $govuk-border-width-mobile variable doesn't make any sense

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1240]
We have a variable called `$govuk-border-width-mobile`.

It's documented as 'Border width on mobile'

However, it's only used in a couple of places:

- The width of the conditional reveal on checkboxes and radio buttons **at all breakpoints**
- The width of the error summary **at all breakpoints**

We should consider renaming or removing this variable.

**Comment by dashouse** [comment]
The 4px border is used in the conditional reveals because it has to be an even number in order to be centred under the 40px checkbox or radio. 5px would put it 1px too far left or right and it was noticeable.

The error summary change is probably not needed.

So I'd say we will need a 4px border, it should just have a different name.
