### ISSUE TITLE
Provide a way to import all macros

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#1278]
Related to https://github.com/alphagov/govuk-prototype-kit/issues/727

We tell people to import each macro individually, for example:

```
{% from "button/macro.njk" import govukButton %}
```

[In the Prototype Kit we've imported all macros](https://github.com/alphagov/govuk-prototype-kit/blob/master/app/views/layout.html) so people don't need to add this line every time.

Another down side to the individual approach is people could copy and paste the example multiple times on the page, which is unnecessary and could be confusing.

With SCSS, we provide a way to import all SCSS, so not providing a way to import all macros seems inconsistent.

## Proposal

We could provide a way to import all component macros, something like:

```
{% include "components/all.njk" %}
```

We would then change the guidance in the Design System to add this line once in your template, say in the production Get Started guide, instead of the import line in every example code snippet.

Potential risk - if Nunjucks actually loads macros into memory at import (we don't know whether it does) then potentially this could use more memory than it should.

**Comment by nickcolley** [comment]
You can also import macros like

```js
{ govukRadios, govukCheckboxes } from 'govuk-frontend/macros'
```

So I wonder if you could have something like

```js
'all' from 'govuk-frontend/macros'
```

Not sure.

**Comment by lfdebrux** [comment]
This is something @aliuk2012 and I would like, as we're currently working on migrating the Digital Marketplace away from its own fork of govuk_frontend_toolkit and onto govuk-frontend.

I've created a branch of govuk-frontend which adds an `all.njk` template: https://github.com/alphagov/govuk-frontend/compare/master...lfdebrux:ldeb-add-all-njk

Do people think this could be turned into a pull request?

**Comment by lfdebrux** [comment]
> Potential risk - if Nunjucks actually loads macros into memory at import (we don't know whether it does) then potentially this could use more memory than it should.

I tried running [nunjucks-cli](https://www.npmjs.com/package/nunjucks-cli) to render template.njk against master and against my branch, and in both cases it used about the same amount of memory, 44 MiB. Actually the version importing individual elements used slightly more, but less than 1 MiB, and I think that's probably within errors.

**Comment by nickcolley** [comment]
I have also done a spike for an 'all.njk' feature. This was in response to talking to HMRC about making it easier for the Prototype Kit extensions.

https://github.com/alphagov/govuk-frontend/pull/1436

**Comment by lfdebrux** [comment]
Interestingly nunjucks devs seem to recommend against using this pattern: 050843

**Comment by nickcolley** [comment]
> because it prevents your application from having proper dependency tree

With regular JavaScript that is sent to users this is a issue since you're sending all of the code when you may only be using a part.

For a server side templating language I'm not sure what the cons are to loading all templates at once, even if they're not needed. I imagine it could slow down the application in certain scenarios? It's not clear.

**Comment by lfdebrux** [comment]
Looking at the docs on `include` for [Nunjucks](https://mozilla.github.io/nunjucks/templating.html#include) and [Jinja](https://jinja.palletsprojects.com/en/2.10.x/templates/#include), I now realise that `{% include 'components/all.njk' %}` will never work, because including a template is defined as including its rendered contents, which is different to importing exported values. Also it seems that there is no way to do an `import` all or `import` without namespacing. I guess you must have realised all this already @nickcolley!

I do think though that this does seem to mean that there couldn't be a way of importing all macros without changing how GOV.UK Frontend is currently used.

**Comment by 36degrees** [comment]
I'm going to close this as we haven't seen demand for it, and there are a number of challenges with the approach as discussed in the comments above.

We have at least managed to avoid the Prototype Kit needing to import all of the components individually, as the config we ship now includes a dynamically generated list of all of the macros:

https://github.com/alphagov/govuk-frontend/blob/93fbf29fd9cab4f294d0ad4f7bd98b83dfa3fc63/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs#L17-L26
