### ISSUE TITLE
Add ability to override or remove Open Graph meta tag in Template

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-frontend#1289]
At the moment `meta property="og:image"` in Template has a hardcoded image path, user should be able to override the image path in the meta tag.

User need explained here: 
- https://github.com/alphagov/govuk_template/issues/137

Split from: https://github.com/alphagov/govuk-frontend/issues/971

Part of https://github.com/alphagov/govuk-design-system/issues/777

## Who needs to know about this
Developer, Mark to review

**Comment by aliuk2012** [comment]
Needed as part of https://github.com/alphagov/govuk-design-system-backlog/issues/185

**Comment by aliuk2012** [comment]
Needed as part of https://github.com/alphagov/govuk-design-system-backlog/issues/185

**Comment by hannalaakso** [comment]
### Proposed solution

I think we should solve this with a breaking change:
```
{% if openGraphImageUrl %}
  <meta property="og:image" content="{{ openGraphImageUrl }}">
{% endif %}
```

We would only set the Open Graph image meta tag if user passes through their own absolute URL - we obviously can't know if the URL is absolute but the requirement should be made clear in the guidance. Whilst the current code allows `assetUrl` to fall back to using `assetPath`, this will only work if the `assetPath` happens to be an absolute URL. It's not clear this happens and going by the discussion in https://github.com/alphagov/govuk-frontend/pull/847, this was mostly implemented so that we could avoid making a breaking change. 

This would also allow for the removal of the meta tag entirely if `openGraphImageUrl` is not set. 

This would also be a good chance to make `assetUrl` a bit more descriptive and call it something like `openGraphImageUrl`.

### Alternative _non-breaking_ solution 

```
  <meta property="og:image" content="{{ assetUrl | default('/assets') }}/{{ opengraphImagePath | default('images/govuk-opengraph-image.png') }}">
```
This would add a new option `opengraphImagePath` whilst retaining `assetUrl` allow the user to do one of the following options:
1. Set the entire absolute url eg. https://domain.com/my-images/article-image-2019.png 
2. Set only the domain url https://domain.com, which gets combined with 'images/govuk-opengraph-image.png'
3. Setting assetPath to an absolute URL which cascades to `assetUrl` and is combined with ‘'images/govuk-opengraph-image.png’

**But** it feels confusing to have to use two variables to set one thing, making it harder to explain in the guidance. The naming is also a bit weird since `assetUrl` is not very descriptive so it wouldn't be clear how it works with something like `opengraphImagePath`.

This approach also wouldn't allow the removal of the meta tag entirely so we'd have to consider another boolean option that would remove the meta tag which wouldn't be ideal.

**Comment by nickcolley** [comment]
I really like your investigation and the options are super clear thanks for doing that Hanna.

I believe that GOV.UK does override this meta tag by making use of the `head` block since the first instance of the metatag is what is used.

You can see this change in the original GOV.UK Template project:

https://github.com/alphagov/govuk_template/commit/204ee88e2c87e7e6db2aa61bf10659c8fdee2c69

With this in mind I would suggest we close this for now and see if anyone runs into any problems with using this approach:

```javascript
{% block head %}
   {{ super() }}
   <meta property="og:image" content="path/to/my/custom/image.png">
{% endblock %}
```

**Comment by hannalaakso** [comment]
Thanks @nickcolley 👍 It's possible to include the meta tag in the `head` block but I think this is now slightly hacky for the current Design System since we already have a documented option `assetUrl` which is used to "Specify an absolute URL for the` <meta property="og:image">` tag image asset." We haven't documented having to use the `head` block to override the meta tag there and there isn't a clear way for users to discover this option.

I think the cleanest and from the user's point of view clearest thing to do would be to do a breaking change. It would also allow for the removal of the meta tag by the user which is a requirement of this card and which can't be achieved cleanly by using the `head` block (unless you include the meta tag in `head` but leave the URL empty which feels messy and could have its own problems).

**Comment by hannalaakso** [comment]
Okay I’ve tried to document this in https://github.com/alphagov/govuk-design-system/pull/1072. I still think that having two different ways of dealing with the tag (use `assetUrl` or set in `head`) depending on what you need to do could be confusing but will ask Mark to have a look at helping us to write this for the docs. We still won’t be a able to remove the Open Graph tag but let’s address that if it comes up.
