### ISSUE TITLE
Tab has bevelled edge

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#1362]
Because the selected tab has the blue (box-shadow) border style applied it does not have the grey border the top.

This implementation has kept the border set to transparent, creating an angled edge where the borders join (doesn't matter that one of them is invisible).

Ideally this would be set to 0px width to remove this effect, however I'm aware that for users that override their colours or can't see the box shadow the selected tab would be open topped.

<img width="396" alt="Screen Shot 2019-05-13 at 15 57 18" src="https://user-images.githubusercontent.com/23356842/58026794-2ced8400-7b0f-11e9-9002-c72465e205a5.png">

Is there anything we can do to keep the clean look of the 0px border-top while still retaining a good looking tab when overriding or inverting colours?

**Comment by 36degrees** [comment]
Not quite what you're asking for, but adding a 1px blue border and removing 1px from the box-shadow gets _closer_…

<img width="348" alt="Screen Shot 2019-05-21 at 15 27 35" src="https://user-images.githubusercontent.com/121939/58104671-10b81880-7bdd-11e9-8d20-0ebfe3a61f6d.png">

😕

**Comment by timpaul** [comment]
Does this help?

https://jsfiddle.net/ThinkingStiff/TvGC5/

**Comment by 36degrees** [comment]
Unfortunately not, because when a user has customised their colours box-shadows become invisible, which means rather than looking like this:

![Screenshot_2019-05-21 Stackoverflow - set css border to end in a 90 instead of a 45 degree angle](https://user-images.githubusercontent.com/121939/58110902-5201f580-7be8-11e9-88ed-f5bde7d2ac9c.png)

We end up with this:

![Screenshot_2019-05-21 Stackoverflow - set css border to end in a 90 instead of a 45 degree angle(1)](https://user-images.githubusercontent.com/121939/58110912-562e1300-7be8-11e9-9ab0-f2259bc797f6.png)

And in the case of our tabs, we end up with something like this:

<img width="1019" alt="Screen Shot 2019-05-21 at 16 50 02" src="https://user-images.githubusercontent.com/121939/58110999-7d84e000-7be8-11e9-8475-fda33635dba2.png">

**Comment by nickcolley** [comment]
I managed to get it 90% working by using floating pseudo elements, but I got proper into the weeds on it and got scared...

**Comment by gunjam** [comment]
How about this? 😅
https://codepen.io/anon/pen/eaeybB

**Comment by gunjam** [comment]
Or: https://codepen.io/anon/pen/MdOQrv

**Comment by nickcolley** [comment]
@gunjam the border-image with a gradient could be a way forward, will give it a go thanks :)

**Comment by nickcolley** [comment]
The new design does not require this CSS anymore so this is no longer an issue.
