### ISSUE TITLE
Use of issue/pull request templates

### ISSUE THREAD

**Issue by htmlandbacon** [alphagov/govuk-frontend#1395]
Opening for discussion

I thought it might be good to add templates for issues and pull requests

https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-your-projects

Largely because I went to do a pull request and had a blank on what to write and make sure everything was covered (specially coming to a project that isn't my own).

Pull request example: https://github.com/stevemao/github-issue-templates/blob/master/questions-answers/PULL_REQUEST_TEMPLATE.md

Issue template: https://github.com/stevemao/github-issue-templates/blob/master/questions-answers/ISSUE_TEMPLATE.md

Appreciate this one might be overkill but figured it was a starting point.

**Comment by nickcolley** [comment]
We have shyed away from this in the past since we want to make sure there's no barriers to opening a pull request.

Our current strategy is to accept that people will raise something incomplete and ask them nicely to do the rest of the work.

That said, there's definitely things that people often miss like updating the CHANGELOG that a pull request template might help.

We could consider putting these prompts as HTML comments that can be deleted which would make them seem more like hints and less like essential things.

```markdown
<!-- If you make a change that is like X you should add a CHANGELOG entry [link] -->
```

**Comment by hannalaakso** [comment]
Reopening issue as it's on our project board under Upcoming sprints.

**Comment by vanitabarrett** [comment]
We have added Github issue templates (PR https://github.com/alphagov/govuk-frontend/pull/2012) and will be trialling them on `govuk-frontend` this month to see how well they work for users and if we get any feedback.
