### ISSUE TITLE
Browser support: No 'official support' for GNU/Linux based web browsers

### ISSUE THREAD

**Issue by iam-TJ** [alphagov/govuk-frontend#1480]
I am surprised, and disappointed, that the Browser Support table in `README.md` does not include any GNU/Linux operating system entries especially as the table is prefixed with "...officially supports ..."

Is this an oversight or are operators of GNU/Linux browsers really left unsupported?

**Comment by nickcolley** [comment]
Heya @iam-TJ !

We try to make sure GOV.UK Frontend works for as many users as possible.

The main browsers we actively test in are in the browser support table you reference, which are based on the types of users that visit GOV.UK, this ensures that we can be pragmatic with our time.

However we expect that GOV.UK Frontend functionality works in most other browsers since we practice [progressive enhancement](https://www.gov.uk/service-manual/technology/using-progressive-enhancement) and build to web standards.

If you do find any issues related to Linux please let us know and we'll see if we can fix them.

As a personal note, I run Linux too :)

I'm going to close this out as I believe this answers your question but please feel free to re-open if you want more clarification.
