### ISSUE TITLE
Checkbox not being categorised as displayed in geb 1.1.1

### ISSUE THREAD

**Issue by adamszymaszczyk** [alphagov/govuk-frontend#1537]
Hi,
We are having an issue with our acceptance tests which checks if a checkbox is being displayed on page.

We use Geb 1.1.1 and it's isDisplayed method checks if the opacity of an element is 0 hence for govuk checkbox it returns false even though the checkbox is visible to the eye, but in code terms is being hidden and replaced/covered by another shape.

This is an issue for us, and think it may be an issue for any frontend libraries or testing software which checks for the zero opacity condition in a similar way.

We are unsure whether this is a wide issue and should be fixed via the design system or is unique to us and requires us to change the way our automated tests work - please could you confirm the best course of action in this instance.

**Comment by 36degrees** [comment]
Hi @adamszymaszczyk,

I don't think there's anything we could do to fix this, so I'd recommend changing the way the tests work if you can. I don't know much about Geb – what exactly is it that you're testing? In most cases asserting on the visibility of the label should achieve the same thing, and if you're testing interaction then clicking on the label should have the same effect as clicking on the input. You should be able to target the label by using `[for="id-of-input"]`.

[Similar issues in Selenium have been discussed previously](https://github.com/alphagov/govuk_frontend_toolkit/issues/388) which may be useful for your reference.

I'm going to close this because I don't think there's anything actionable for us to do, but if you continue to have problems then please do feel free to re-open it.
