### ISSUE TITLE
date-input: id is documented as optional but used as required to create hintId and errorId

### ISSUE THREAD

**Issue by dabd** [alphagov/govuk-frontend#1557]
In the `date-input` component [`id` is documented as optional](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/date-input/date-input.yaml#L4) but [treated as a required parameter when creating the `hintId`](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/date-input/template.njk#L32) and [`errorId`](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/date-input/template.njk#L43) (if it is not provided it will generate an id starting with hyphen, which is probably not the intended result).
It is treated as optional [elsewhere](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/date-input/template.njk#L56).

Should it be considered as a required parameter instead?

In the `radios` component when `idPrefix` is not supplied [it falls back to using `name`](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/radios/template.njk#L8).  Does it make sense to use the same approach here?

Same problem here: https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/tabs/template.njk#L3

**Comment by StheffanyHadlich** [comment]
Can I help with this issue?

**Comment by nickcolley** [comment]
Heya @StheffanyHadlich!

Thanks for offering to help out, we think this issue is more than just documentation so the GOV.UK Design System team will pick this up.

We have some first timer issues over on the GOV.UK Design System website repository if you're interested in contributing there: https://github.com/alphagov/govuk-design-system/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

**Comment by StheffanyHadlich** [comment]
Oh, thank you

**Comment by kellylee-gds** [comment]
Review from @m-green
