### ISSUE TITLE
"GOV.UK" text in header doesn't resize as text

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1568]
Font size for "GOV.UK" text in the header is only set in `px`, not in `rem` (in `.govuk-header__link--homepage`). 

This means that it doesn't resize when text size is changed by user in Chrome or IE.

![Screen Shot 2019-09-12 at 16 17 02](https://user-images.githubusercontent.com/5007934/64797150-d05c1c00-d578-11e9-848a-3779df7a9094.png)

It should be legible to all users as part of branding.

**Comment by nickcolley** [comment]
I had a little poke at this, seems like we can definitely scale it based on the text but it almost feels like it's not that useful to do?

Here is an extreme example where the logo is very big, and since it's just a logo it doesnt seem important to be so huge.

<img width="1087" alt="Screen Shot 2019-09-16 at 14 10 54" src="https://user-images.githubusercontent.com/2445413/64960782-dfe6a800-d88b-11e9-8389-c0fc62e2d508.png">

**Comment by hannalaakso** [comment]
Discussed with the team. We don't have evidence that this is a problem so closing issue.
