### ISSUE TITLE
Why is the font set on many CSS classes?

### ISSUE THREAD

**Issue by daniel-ac-martin** [alphagov/govuk-frontend#1610]
The SCSS code seems to be written such that things that I would expect to be set site-wide (on the body tag) are set on many individual classes.

Why is that?

(Apologies if that is a silly question!)

I ask because it would be useful to re-use the SCSS code on non-GovUK websites in which we are required to avoid the New Transport font.

**Comment by nickcolley** [comment]
Heya @daniel-ac-martin,

Not a silly question, in most projects you'd be right to expect this as a site-wide setting that cascades.

The main reason we do this is since GOV.UK Frontend is design to work without conflicts alongside existing CSS in projects, specifically the older projects that GOV.UK Frontend is replacing.

You can change the font by setting the `$govuk-font-family` Sass variable when you import GOV.UK Frontend.

We have another issue around documenting how to do this, since it's not clear right now: https://github.com/alphagov/govuk-design-system/issues/1019

Let me know if this helps you.

**Comment by daniel-ac-martin** [comment]
Thanks for the info @nickcolley.
