### ISSUE TITLE
Can't add custom class to character count

### ISSUE THREAD

**Issue by LBHELewis** [alphagov/govuk-frontend#1649]
Currently it's not possible to add a custom class to the character count wrapper (`.govuk-character-count`) because the `classes` property is being used for the nested textarea instead. This goes against the convention in other components. 

It would be helpful for us to have `classes` apply to the `.govuk-character-count` (or if this would be a problem because of introducing a breaking change then it would be helpful to have a new property that gives the ability to add custom classes to `.govuk-character-count`). In our use case we are re-skinning `govuk-frontend` for Hackney Council (see https://github.com/lbhackney-IT/lbh-frontend) and would like to alter the spacing around the character count component and to style the hint inside it without targeting solely `.govuk-*` classes (a convention that we're trying to stick to). There are ways of getting round this (not least breaking our convention in this case) so it isn't absolutely crucial to us, but would be nice if it could work the same way as all other components.

**Comment by nickcolley** [comment]
Hey Emma,

We recognise that the api for this component is inconsistent with the rest of our components.

To make it consistent we'd need to make a breaking change.

For this reason we'll see if more of our users run into this issue, and then consider changing this.

Let us know if this causes blockers for you, and we can reconsider this decision.

**Comment by vanitabarrett** [comment]
As discussed in the v4 prioritisation, this component does work differently to our other components, so maybe it's ok that this is reflected in the macro options. This problem is wider than just classes, e.g: the macro options also let you pass in `id` and other HTML attributes that apply to the textarea, not the parent. There are probably 3 options here:

1. We rename `classes`, `id` etc to `textareaClasses`, `textareaId` etc and introduce new macro options to apply to the parent that follow the macro options for our other components
2. Introduce new macro options that apply to the parent, e.g: `parentClasses`, `parentId`. This would not be a breaking change
3. Revisit the character count component and consider rolling it into the textarea component

Probably needs more investigation. It would also be good to know if this is something that causes an issue for a lot of our users, or if it behaves as expected despite being different to other design system components.

**Comment by colinrotherham** [comment]
This is now ready for review as part of https://github.com/alphagov/govuk-frontend/pull/4566
