### ISSUE TITLE
Select box validation styles are not applied properly

### ISSUE THREAD

**Issue by FionaHolder** [alphagov/govuk-frontend#1787]
A select box with the usual error CSS classes applied to it does not get the red border as expected:

![image](https://user-images.githubusercontent.com/5195836/79755138-81e1dd80-8310-11ea-97b4-20f316834a6c.png)

This is because the `.govuk-input--error` class that applies the red border is overridden by the `.govuk-select` class, which applies a black border.

**Comment by 36degrees** [comment]
Hi Fiona,

Modifiers (the classes that contain double hyphens `--`) are always designed to be used with their 'matching' component class (the bit before the double hyphens).

Therefore, when a select is in an error state, you should use the `govuk-select--error` modifier rather than the `govuk-input--error` modifier. There's also, for example, a `govuk-textarea--error` for the textarea component.

If you use `class="govuk-select govuk-select--error"` then it should display as expected, with the thick red border.

![image](https://user-images.githubusercontent.com/121939/79755850-a7231b80-8311-11ea-9837-c20c89252f83.png)

I'm going to raise an issue on the Design System repo to provide an example of the Select component in its error state, as it seems like an oversight that we don't have one there.

Otherwise, I'm going to close this issue, as I don't think there's anything we need to change, but please let me know if you have any problems, or I've missed something or misunderstood.

**Comment by FionaHolder** [comment]
Ah thank you, you're absolutely right - there wasn't an example in the docs so I've applied the wrong CSS class. Much appreciated :)
