### ISSUE TITLE
Add 'None of these' feature to checkboxes

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#1795]
## What

Add guidance and possibly code to [checkboxes](https://github.com/alphagov/govuk-design-system-backlog/issues/37) to allow a 'None of these'

## Why

We previously had this guidance in Dropbox Paper. The alternative is the user selects no checkboxes and clicks continue, which is an implicit answer. This is arguably less clear than an explicit answer, and there is a risk the user clicked continue accidentally.

**Comment by alexnewmannn** [comment]
@timpaul We've not yet got any client side javascript to deselect or disable other checkboxes when 'none' is selected. This may be because with our question there isn't really room for interpretation, but can't say for certain. When we validate server side we return an error that you can't select 'none' and something else. I've just had a look and we've seen that error 23 times in the past 6 and a bit months which is pretty low. We are adding a new page with this pattern again so will be keeping an eye on the errors for this page and push to add a js feature. It's worth noting that our events vs unique events (meaning one checkbox being clicked more than once) is for the most case almost identical, meaning very few people are changing their mind once selected. So from our perspective it seems like having no client side javascript is working fine and server side validation is sufficient for when js isn't available.

**Comment by joelanman** [comment]
I'd suggest an error message something like:

"You cannot select 'None of these' and other options"

**Comment by alexnewmannn** [comment]
@joelanman Yeh, we currently have `Cannot select 'none' and a benefit` when none and something else is selected and `Select the benefits they were getting or waiting to hear about, or select 'none'` when nothing is selected, which both seem to work fine when they do appear.

**Comment by vanitabarrett** [comment]
GOVUK (specifically @alex-ju ) have added this as a component in their own component library: https://github.com/alphagov/govuk_publishing_components/pull/1478

**Comment by 36degrees** [comment]
We'll need to think about conditional reveals when we do this – at the minute the logic for checkboxes assumes that we only need to sync the conditional reveal state for the checkbox that was clicked:

https://github.com/alphagov/govuk-frontend/blob/6e3a9920ba1785c0f5cfaf4d70c8626f1836a109/src/govuk/components/checkboxes/checkboxes.js#L68-L77

We'll also need to think about scope – do we scope to the immediate module, or make it act like a radio button and deselect any checkboxes with the same `name` in the same `form`?

**Comment by edwardhorsford** [comment]
We [added something for this in my service](https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/psd-web/app/assets/javascripts/mutually_exclusive.js).

More abstractly it creates 'mutually exclusive' groups - which get defined using data attributes on each checkbox. When a checkbox is checked, checkboxes in groups other than the current one get unchecked. The idea for this came from someone on the cross gov slack - but I don't remember who suggested it (they were doing similar).

This generically supports where you might have more than one group. eg:
```
[] a
[] b
[] c
or
[] d
[] e

```

**Comment by joelanman** [comment]
example from the census
<details>
  <summary>Alt text</summary>
Do any of the following people also live at [address] on Sunday 21 March 2021?

Who to include
 Do any of the following people also live at 47 East Road, London on Sunday 21 March 2021?
Select all that apply. You can select more than one for each person

Family members and partners 
Include babies born on or before 21 March 2021, children, students and schoolchildren who live away from home during term time


Housemates, tenants or lodgers
 

People who usually live outside the UK who are staying in the UK for 3 months or more


People temporarily away 
For example, working away, on holiday, in the armed forces, living in an establishment such as a care home for up to 6 months, abroad for up to a year


People staying temporarily who usually live in the UK but do not have another UK address 
For example, UK residents between addresses or currently without a home
Or

Or, None of these apply, I am the only person who usually lives here
</details>

![screenshot of census](https://user-images.githubusercontent.com/1132904/111459696-f258d080-8712-11eb-8b87-8ff10a9dbcc6.png)
