### ISSUE TITLE
Inline script in template.njk blocked by CSP

### ISSUE THREAD

**Issue by chrift** [alphagov/govuk-frontend#1811]
We are looking to add a Content Security Policy to our application, but are currently unable to do so without specifying the `unsafe-inline` policy, due to the inline script tag in template.njk which adds the `js-enabled` class to the body. 

Could this instead be part of the `GOVUKFrontend.initAll` function to avoid having an inline script?

**Comment by chrift** [comment]
Found [this issue](https://github.com/alphagov/govuk-frontend/issues/1657) and have added the sha hash to our CSP

**Comment by 36degrees** [comment]
Hi Chris,

Thanks for raising this. I'm going to re-open your issue and stick a triage label on it for our team to discuss, as I think we should provide better documentation around this so you don't have to go digging through past issues to find the solution!

**Comment by hannalaakso** [comment]
To resolve this, we’re going to: 
- document the recommendation that teams allow the hash of the inline script tag in their CSP under JavaScript in GOV.UK Frontend developer docs 
- treat any changes to the hash as a breaking change 
- add a test to GOV.UK Frontend to check that the script tag hasn’t changed and if it does, what to do about it

This approach seems low risk since we’re not introducing any breaking changes, and we don’t expect the script tag to change much, if ever, so the hash should stay fairly static over time. 

We could in the future consider supporting nonces if we had evidence that it would be useful to teams.

We also considered publishing the hash in a file in the GOV.UK Frontend npm package but at the moment it isn’t clear how doing so would benefit teams.

**Comment by hannalaakso** [comment]
Resolved by https://github.com/alphagov/govuk-frontend-docs/pull/70
