### ISSUE TITLE
Focused link clipped in Chrome – Footer component, two column list layout

### ISSUE THREAD

**Issue by danacotoran** [alphagov/govuk-frontend#1888]
This issue seems to occur only when one of the columns has more navigation items than the other column (it's fine when the columns are equal).

What happens is that for some reason when the last link on the larger column is in focus, the link gets clipped.

It seems to have something to do with how Chrome applies the `columns` CSS properties. 

## Normal

<img width="821" alt="Screenshot 2020-07-29 at 16 48 13" src="https://user-images.githubusercontent.com/7116819/88822139-6a41ad00-d1bb-11ea-84ea-dbe62294c78d.png">

## With two unequal columns
<img width="805" alt="Screenshot 2020-07-29 at 16 48 28" src="https://user-images.githubusercontent.com/7116819/88822157-6ca40700-d1bb-11ea-9267-330e4291016d.png">

**Comment by 36degrees** [comment]
Looking at https://stackoverflow.com/questions/17881923/box-shadow-trimmed-in-css-columns-in-chrome, `transform: translateZ(0);` seems like it might fix this.

(Think this is at least vaguely related to https://github.com/alphagov/govuk-frontend/issues/1284, so in the longer term we might end up moving away from using CSS columns anyway)

**Comment by vanitabarrett** [comment]
As mentioned in v4.0.0 prioritisation, we're going to do a timeboxed investigation into https://github.com/alphagov/govuk-frontend/issues/1726 and https://github.com/alphagov/govuk-frontend/issues/1539 first. It's possible that this issue might be fixed if we switch to a different layout system in the footer. We should make sure we keep this card in mind when doing any testing during that investigation.

**Comment by 36degrees** [comment]
I think the issue [might have been fixed in Chrome 102](https://bugs.chromium.org/p/chromium/issues/detail?id=133029#c27).

Are we happy to close this on that basis?

## Chrome 101

<img width="1005" alt="Footer with an odd number of links in a two-column layout. The last link in the first column is focused, but the black underline is thinner than it should be." src="https://user-images.githubusercontent.com/121939/173627621-cb4bc81a-7202-4d4e-a400-912731595fe0.png">

## Chrome 102

<img width="1005" alt="Footer with an odd number of links in a two-column layout. The last link in the first column is focused and looks correct." src="https://user-images.githubusercontent.com/121939/173627617-d85a55da-0ad8-4294-9a57-0fc5d36900f1.png">

**Comment by vanitabarrett** [comment]
Happy to close if this has been fixed @36degrees

**Comment by 36degrees** [comment]
@matthillco meant to say – thank you very much for pointing us towards your fix, really appreciate it. However it looks like the issue has been fixed as of Chrome 102 so it shouldn't be needed now 🤞🏻
