### ISSUE TITLE
Define print styles for panel component

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1946]
As raised by a user on Slack, the lack of print styles means that the panel component prints with light grey text on white:

![image](https://user-images.githubusercontent.com/121939/79877291-f9347180-83e3-11ea-9e12-9bc90dbd2ff5.png)

I believe this is the browser’s ‘best effort’ to make it printable – by default, browsers will remove background colours from things when printing them, and because the text would then be white-on-white it’s making the text grey.

_Originally posted by @36degrees in https://github.com/alphagov/govuk-frontend/issues/573#issuecomment-617212704_

**Comment by terrysimpson99** [comment]
Further to the issue mentioned by 36degrees today. That's quite a low contrast. Has it passed a test for accessibility at A or AA? If not, we'll have to stop using it.

**Comment by 36degrees** [comment]
Hi @terrysimpson99,

I'm not entirely sure I follow you, sorry – the low contrast of the text is what this issue is trying to address?

The associated PR adds print styles for the panel component which changes the text to black and adds a border:
https://github.com/alphagov/govuk-frontend/pull/1947

**Comment by terrysimpson99** [comment]
Aha, I didn't see your PR. If the end result is black text on a white background then that should make it accessible. Hurray and thanks for your work! Two more questions:
(1) When/how will it be available?
(2) Can you make the printed panel consume less vertical space? If reducing the printed size means reducing the online size then so bit it. The large text and large vertical spacing in the panel means some of our users print two pages instead of just one. The large panel ext doesn't look bad online but it looks a bit like overkill in a printout, particularly when we make the body text 14 point. (and looks a little odd in paper form), see example below: 
![image](https://user-images.githubusercontent.com/48089049/92407089-90029000-f131-11ea-9244-0328720d231a.png)

These are other issues to be dealt with separately, I'm delighted you're increasing the contrast.

**Comment by 36degrees** [comment]
Hi Terry,

The change to the panel component's text colour and border will be included in 3.9.0 which should be released in the next couple of weeks.

Would you mind raising the size of the panel component when printed in the issue #573? That's something we'll need to look at alongside the rest of the print styles.

Ollie

**Comment by terrysimpson99** [comment]
Thanks. I've commented at #573
