### ISSUE TITLE
Identify potential changes to conditional reveals for research

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1992]
## What

Identify what potential changes to the conditional reveals on radios and checkboxes we might want to prototype and test in user research.

## Why

There are a [few known issues with conditional reveals, as described in the epic](https://github.com/alphagov/govuk-frontend/issues/1991). There are no simple fixes, so we're likely to want to test and potential changes in user research.

## Done when…

- [ ] Desk research for which assistive tech does and does not support aria-expanded on conditional reveals
- [ ] Chosen which use cases are the most appropriate to test in the research prototype. [Ed's examples on slides 53 onwards should help](https://docs.google.com/presentation/d/1AaMbTwmj1SMDa8GaLAYKxCR4ZJYdS5qcRdb_aKYFCLA/edit#slide=id.g9bb3205e84_0_318).

**Comment by CharlotteDowns** [comment]
## Upcoming user research
We are going to test the existing components that use conditional reveal, ([checkboxes](https://design-system.service.gov.uk/components/checkboxes/) and [radios](https://design-system.service.gov.uk/components/radios/)), in order to establish what works well and what works less well. 

Once we have that understanding, we will be in a better place to prioritise design and development changes to the components.

**Comment by CharlotteDowns** [comment]
We have decided to take the component 'as-is' to user research in November 2020. The two versions of the component we are going to test are:
1. [contact details example (as seen in the Design System](https://design-system.service.gov.uk/components/radios/#radios-with-conditionally-revealing-content-example)
2. a fieldset example where we will use either a date or address input.
