### ISSUE TITLE
Should grid be a component?

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#201]
hey folks, I've been thinking about our grid usage, and it's something that tends to be used across component boundaries.

So I was wondering if they should actually be objects and not components?

E.g. `govuk-o-grid` instead of `govuk-c-grid`

As per https://github.com/alphagov/govuk-frontend/blob/master/docs/coding-standards/css.md#objects-o-

**Comment by gemmaleigh** [comment]
Hi Nick,

At the moment we have globals and components. 

We were trying to avoid another "type of thing", by adding a distinction for layout too.

I agree, it would be good to have an ITCSS style "object" prefix (that's why it exists in the docs) but I'm not yet sure how this fits with how we describe components in the Design System. 

I'll leave this open as one for us to investigate.

**Comment by nickcolley** [comment]
We should make sure our docs reflect how we're building even if it means we move away from ITCSS.

I think the distinction is a good one because it communicates risk associated with changing something.

**Comment by 36degrees** [comment]
We moved to the grid being a layout in #290 so closing this.
