### ISSUE TITLE
Conditional reveal for hidden radio-button associated input not working in govuk-frontend release 3.10.1

### ISSUE THREAD

**Issue by ciarancolgan** [alphagov/govuk-frontend#2066]
## Description of the issue
Using release 3.10.1 (https://github.com/alphagov/govuk-frontend/releases/tag/v3.10.1) and importing the 'govuk-frontend-3.10.1.min.js' file into the project, the conditional reveal of a hidden input associated with a radio button (as per: https://design-system.service.gov.uk/components/radios/conditional-reveal/index.html) doesn't work - Chrome Dev Tools show no event listeners hooked up to the radio input. 
If I take the Js (unminified) from that design-system.service.gov.uk demo site and swap it in locally, it does work. If i further manually minify this demo site Js file (via e.g. https://javascript-minifier.com/), it continues to work. 
I do note a not insignificant difference in file size between the supplied minified file and the manually minified file. 

## Environment (where applicable)
Windows 10
Tested on 
Chrome: 87.0.4280.88 
Edge: 87.0.664.60 
Firefox 83

**Comment by 36degrees** [comment]
Hi Ciaran,

Can you please double check that you're following the [instructions on installing using precompiled files in the Frontend Docs](https://frontend.design-system.service.gov.uk/install-using-precompiled-files/#install-using-precompiled-files).

From what you've told me, it sounds like you might not be initialising the JavaScript in your application by calling `GOVUKFrontend.initAll()` – which should be done before the closing `</body>` tag.

You'll also need to make sure you're including the `<script>` tag that sets up the `js-enabled` class on the `<body>` (immediately after the opening `<body>` tag) so that styles are applied correctly.

**Comment by ciarancolgan** [comment]
Thanks @36degrees! I wasnt calling window.GOVUKFrontend.initAll() - thanks a lot mate. Closing.
