### ISSUE TITLE
Add visual regression testing

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2070]
## What

Add visual regression testing to GOV.UK Frontend

## Why

This came up as part of a ['tech & ops health check' exercise](https://github.com/alphagov/govuk-design-system/issues/1395) the team ran in November 2020, as part of the 'testing – pre-deployment' practise.

We scored ourselves as 'good' for that practise, but said that we were 'moderately concerned' about it as we know there are some areas that could be improved.

Visual regression testing was highlighted as one area we'd like to add to GOV.UK Frontend. We believe that it will help us to avoid shipping unintended changes to the design or layout of components, especially in non-default contexts (for example, changes that are only visible when using compatibility mode, or if the user is using Windows High Contrast Mode).

## Done when

- [x] Trial Percy in GOV.UK Frontend repo - in progress until end of Q4
- [x] Revisit how trial went and decide next steps

**Comment by vanitabarrett** [comment]
Percy seems to be working pretty well for our team. People are either looking at the screenshots and finding them useful, or they haven't needed to do so yet - probably due to the nature of the things they've been working on.

Given we're only using ~43,000 screenshots per month in total (across the GDS account), we're not near our monthly limit so it makes sense to keep Percy running.

I've raised a new card for exploring other scenarios in which we may want to generate screenshots https://github.com/alphagov/govuk-frontend/issues/2593 which we may want to pick up in future.
