### ISSUE TITLE
Test cookie banner component with assistive technologies

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#2105]
## What
Now that we have access to AssistivLabs and BrowserStack, we can use that to test the cookie banner with assistive technologies more generally and check there aren't any issues we weren't aware of.

## Why
To test against different assistive technologies; to understand where the cookie banner may need any improvements

## Who needs to know about this
Developers

## Done when

Tested with the following and documented any issues:
- [x] JAWS 2020 / Chrome
- [x]  JAWS 2020 / IE11
- [x]  NVDA 2020.3 / Firefox 81
- [x]  NVDA 2020.3 / Chrome 86
- [x]  Voiceover / Safari (macOS Catalina)
- [x]  Voiceover / Safari (iOS 14)
- [x]  Talkback / Chrome 86 (Android 10)
- [x]  Windows Magnifier or Apple Zoom (screen magnifiers) | Latest | Any

**Comment by vanitabarrett** [comment]
Spreadsheet to record testing results: https://docs.google.com/spreadsheets/d/1ExFstuvy_F8T4MfU2AIoMJRZdXSe9RZC0NEDaCGiLS4/edit#gid=0

**Comment by vanitabarrett** [comment]
Issue with JAWS + Chrome and JAWS + IE where the confirmation message is not read out and the accept/reject button is read out again instead. 

Some testing around this issue documented here: https://docs.google.com/document/d/1GdZAIZiRmaFQgiKG7Mg3smxWxaOLeb8VzvXqseVZ0no/edit#

Copying @hannalaakso 's findings from Slack before they get lost:

 I might have partially got to the bottom of the replacement message not being read out on Jaws. I think programatically focusing the container which has role=alert on it on the client side example when the page hasn’t reloaded breaks Jaws and also NVDA, depending on the markup used (I’ve moved attributes around to test what works). Simply relying on role=alert makes Jaws+Chrome, NVDA+FF, NVDA+Chrome, Mac+Voiceover work correctly (I haven’t tested iOS and Talkback).
Unfortunately I can’t get IE11+Jaws to work, although interestingly focusing the cookie banner container itself makes IE11 at least read out the label of the banner. I also tried moving the focus one div above the container that has role=alert to see if IE11 would pick that up but couldn’t get it to work. I suspect the cookie banner container works as it’s a landmark and has a label. If IE11 doesn’t support role=alert in this way then trying to support IE11 would be be extra work for service teams by doing something with programmatic focus and modified aria-labelledby maybe... The GOV.UK implementation also doesn’t work with IE11+Jaws.
I think we should test if we’re happy that role=alert alone works for the combinations we want to support and then remove the bits from the client side guidance about programmatic focus. I think we could even just set role=alert on the replacement message containers in the markup, that’s how I’ve been testing this, I don’t think there’s a need for teams to do that in JS.
I haven’t got to the bottom of the server side replacement message as I’ve only just started looking at it. NVDA+FF seems to work fine without programmatically focusing but Chrome+Jaws doesn’t. It’s funny since this should be in theory be similar to what we do with the notification banner focus. One thing we do differently is the labelling: I can’t remember if in our acceptance testing for the notification banner it was enough for the heading that’s linked with aria-labelledby to be read out when it was focused or if the content of the banner had to be read out too. (The other thing is that our message div that gets the focus and has role=alert is quite deeply nested with the grid, it might affect whether screen readers can find the content on the server side implementation?) Probably worth digging into a bit more.
