### ISSUE TITLE
Create additional link styles to align with buttons on cookie banner 

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#2107]
## What
We now have three inline actions in the cookie banner. New styles may need to be introduced to keep all actions aligned, equally spaced and consistent.

The 'accept...' and 'reject...' actions are buttons but the 'View and set cookie preferences' action is a link and is visually different from the two buttons.
## Why
Users need to understand that the three actions are related and that their cookie preferences can be altered to selectively opt in and out of additional cookie types.
## Who needs to know about this
Designers, developers
## Further detail
- The focus styles for links are also different and should be looked at as part of this work.
- The primary button padding may also need to be reviewed if it is to have consistency with the currently proposed button for rejecting cookies.
## Done when

- [x] Decided on content for buttons and links in the cookie banner.
- [x] Decided on styling for the 'reject...' button within the banner.
- [x] Researched and documented use of button alongside links in services across gov.
- [x] Decided if this is an adjustment to the styles in the component or more universally to inline links.
- [x] Adjustments to the styles of the links and buttons to create consistency across desktop and mobile.

**Comment by vanitabarrett** [comment]
Update: there was a conversation on Slack yesterday about styling the 'Hide' link in the confirmation banner as a button instead of a link.

**Comment by CharlotteDowns** [comment]
##  Design decisions

Based on the [working group feedback for the cookie banner](https://github.com/alphagov/design-system-team-internal/projects/7#card-51501865) we prototyped moving the 'view cookies' link onto a separate line beneath the 'accept...' and 'reject...' buttons. These prototypes use an earlier draft of the cookie banner guidance but with updated button and link content.

**Inline**
<img width="1336" alt="Accept analytics cookies button, Reject analytics cookies button and view cookies link all inline within the banner" src="https://user-images.githubusercontent.com/56260216/105172310-55fdbd80-5b17-11eb-844c-704cc22cad79.png">

**New line**
<img width="1398" alt="Accept analytics cookies button and Reject analytics cookies button are inline. The view cookies link takes a new line underneath within the cookie banner" src="https://user-images.githubusercontent.com/56260216/105172259-41b9c080-5b17-11eb-8d40-30662fffed70.png">

We have made the decision to proceed with the inline version of the buttons and link. This makes the assumption that users may be confused about the relationship of the links with the buttons, possibly even mistaking it for an additional option or next step. If you have any feedback or user research that can help us improve on this please let us know.

---

### Margins

We are suggesting adding the class `govuk-!-margin-right-2` to the first button 'Accept analytics cookies' and no additional spacing styles to the 'Reject analytics cookies' to space the buttons equally with the margin styles of the 'View cookies' link.
![Cookie banner margins between buttons and links](https://user-images.githubusercontent.com/56260216/105174594-b2161100-5b1a-11eb-9ff9-ed39bba84454.png)

Other points to note:
- We need to decide on the responsive behaviour of the inline components; two buttons and a link. A suggestion would be to wrap the buttons `govuk-grid-column-full` instead of `govuk-grid-column-two-thirds` as this only causes one break point instead of two as the screen size gets smaller.
- The margin styles for the inline link need to change when it moves to a line on it's own.
- We need to confirm the vertical margins between the buttons on mobile view where they take 100% width of the screen.
