### ISSUE TITLE
Review `theme-color` and `mask-color` usage in Safari 15 (incl. iOS 15 / iPad OS 15)

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2311]
### `theme-color`

We currently have a `theme-color` meta tag set to `#0b0c0c`:

https://github.com/alphagov/govuk-frontend/blob/3c3902e48b73e049a3b165d40e18104c1fda049a/src/govuk/template.njk#L12

Previously, this was only used by Chrome on Android devices to set the background color of the browser chrome:

![Screenshot 2021-08-13 at 09 41 54](https://user-images.githubusercontent.com/121939/129330033-1b0e2ca9-6b8c-4956-8d6b-05ad9baa0b35.png)

However, Safari 15 (currently in public beta) now uses the [`theme-color` meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) to [set the color for both the tab bar background and the over-scroll area](https://developer.apple.com/documentation/safari-release-notes/safari-15-beta-release-notes):

![Screenshot 2021-08-13 at 09 29 09](https://user-images.githubusercontent.com/121939/129328677-2a7668ca-e282-43c1-a6f3-94aa76c96434.png)
![Screenshot 2021-08-13 at 09 29 16](https://user-images.githubusercontent.com/121939/129328688-5230a84b-b342-4c3d-9504-cf35a940050c.png)

Previously, the over-scroll area used the background colour of the `<body>` element (`#ffffff`):

![Screenshot 2021-08-13 at 09 45 31](https://user-images.githubusercontent.com/121939/129330602-c25c1306-00d3-42a5-9d6e-4609c33def5d.png)
![Screenshot 2021-08-13 at 09 45 35](https://user-images.githubusercontent.com/121939/129330587-5f5b07ad-a532-4936-8e39-449f77575bab.png)

Review the current `theme-color` and check we're happy with how it's applied in these new contexts.

### `mask-color`

The [pinned tab icon for Safari on macOS](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html) also uses a mask color of `#0b0c0c`. Unfortunately this means when the tab is pinned and active, the icon would be invisible, so Safari is adding a white background to the tab:

![Screenshot 2021-08-13 at 09 53 20](https://user-images.githubusercontent.com/121939/129331740-cda299ab-e40a-4f79-9099-3b3a8d3d28ba.png)

Review the `mask-color` for the pinned tab icon and work out if there's something better we can do.

## Why

This is the first time that the `theme-color` has affected the browser chrome in a desktop browser, where the browser chrome is more prominent, and the first time that it's been used for the over-scroll area.

This is also the first time that the `mask-color` and the `theme-color` interact.

## Further detail

- [Design for Safari 15 (Video)](https://developer.apple.com/videos/play/wwdc2021/10029/)

## Who needs to know about this

Designers

## Done when

- [x] Browser chrome and overscroll area reviewed in iOS / iPad OS 15
- [x] Browser chrome, overscroll area and pinned tab icon reviewed in Safari 15 on macOS
- [ ] Alternatives considered and tested
- [ ] Issues written up for any changes we want to make

**Comment by 36degrees** [comment]
Example video from iOS 15 beta showing the browser chrome and over-scroll area:


https://user-images.githubusercontent.com/121939/129335418-edf85f08-3021-4260-b60e-0550bc2924e4.mov

**Comment by querkmachine** [comment]
Since the betas, applying the `theme-color` to the browser chrome has been changed from an intended default setting to an opt-in one. The contexts in which it is applied have also changed between the betas and release versions.

The means of opting-in is slightly different across each OS, and the end result works slightly differently in iOS. The option has also been limited to only certain tab layout modes on macOS and iPadOS.

## Safari on macOS 
In macOS, this option is now only available if the 'Compact' tab layout is enabled.

1. Open the preferences in Safari settings. In the menu bar this is under Safari → Preferences...
2. In the 'Tabs' tab and under the 'Tab layout' heading, click the 'Compact' option.
3. In the 'Advanced' tab and under the 'Accessibility' heading, check the 'Show colour in compact tab bar' option.

![The 'Tabs' setting page within Safari, with the 'Tab layout: Compact' option highlighted.](https://user-images.githubusercontent.com/1253214/161717118-66f693c8-dace-43ea-8172-ed1416a9f09b.png)

![The 'Advanced' setting page within Safari, with the 'Show colour in compact tab bar' option highlighted](https://user-images.githubusercontent.com/1253214/161717053-ab175690-5335-469d-a45c-6dd0cee00a1c.png)

## Safari on iPadOS
Safari on iPad works similarly to as on macOS, though the location and naming of the settings is slightly different. 

1. Open the Settings app.
2. In the left pane, scroll to the 'Safari' option and select it.
3. In the right pane, scroll to the 'Tabs' section and select the 'Compact Tab Bar' option.
4. In the right pane, continue scrolling to the 'Accessibility' section and activate the 'Show Colour in Compact Tab Bar' toggle.

There is, in my experience, a bug in iOS 15.3 where Safari will colour the tab bar when the 'Compact Tab Bar' option is first enabled, even if the 'Show Colour' toggle is set to off. Switching the toggle on and off again seems to fix this. 

![Safari settings on an iPad, showing the 'Compact Tab Bar' layout option.](https://user-images.githubusercontent.com/1253214/161723914-b115b8b1-5d03-4b8f-b605-a6a382027f21.jpeg)

![Safari settings on an iPad, showing the 'Show Colour in Compact Tab Bar' option.](https://user-images.githubusercontent.com/1253214/161723982-68ba367f-f817-47be-8181-0e81ecf3b589.jpeg)

## Safari on iOS 
On iOS, this functionality is universally controlled by a single 'Allow Website Tinting' Toggle. 

Colour tinting is applied regardless of whether the address bar is positioned at the bottom ('Tab Bar' in Settings) or top ('Single Tab') of the screen. Tinting is always applied at the top of the browser, behind the status bar content (time, battery, etc.) and notch, on notched devices. 

Instead, these settings only alter _when_ the tinting occurs. With 'Tab Bar', the colour is always present; for 'Single Tab', it is only applied when the browser UI collapses, such as when scrolling down the page. 

![Safari settings on an iPhone, showing the 'Allow Website Tinting' toggle.](https://user-images.githubusercontent.com/1253214/161724873-e5329482-21cc-438a-b7f3-aeb438a58a33.jpeg)

**Comment by querkmachine** [comment]
@Ciandelle and I have agreed that the current colour and iconography seem to be the best they can be at this time, and that we aren't going to take any further action on this for the time being.
