### ISSUE TITLE
Review accordion bug on mobile with summary focus state

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2322]
## What
There is an issue with the focus state on mobile when there are multiple lines in the summary, where the focus state underline is rendered as a thin line

![Screenshot 2021-08-19 at 18 36 39](https://user-images.githubusercontent.com/5007934/130117067-cd706761-e722-4fa8-8937-5f70c7bbf9d0.png)

This impacts Android and Samsung Internet as iOS doesn't show the focus style (but the issue can be replicated in desktop Chrome emulator too, for ease of debugging).

## Why
We should align the focus state with the GOV.UK style, at the moment it looks a bit broken.

## Who needs to know about this
Developers, designer

## Done when

- [ ] Focus state correctly rendered on Android
- [ ] Focus state correctly rendered on Samsung Internet

**Comment by hannalaakso** [comment]
It seems that the issue is the font size and line height set in the enclosing heading which very slightly seems to impact line heights inside of it, even when they're being set explicitly in the enclosed elements.

We explicitly set these properties to stop browser default stylesshets, or other stylesheets, interfering with the h2 as it's not using the govuk-heading-m class. See https://github.com/alphagov/govuk-frontend/pull/1796

Think we need a bit more investigation to understand why the heading values are impacting the enclosed elements.

**Comment by vanitabarrett** [comment]
I've been playing around with removing the two explicitly set line-heights on the button and the toggle:

```scss
.govuk-accordion__section-button {
    @include govuk-text-colour;
    @include govuk-font($size: 24, $weight: bold, $line-height: 1.25);
    display: block;
    margin-bottom: 0;
    padding-top: govuk-spacing(3);
}

.govuk-accordion__section-toggle {
    @include govuk-font($size: 19, line-height: 1);
     color: $govuk-link-colour;
}
```

The margin between the summary list and the heading and toggle needs increasing as a result so that there's a gap between each (in these screenshots, it's been increased to `8px`), but this does seem to fix the issue with the focus state. See below for screenshots of before and after.

## Before vs After
<img width="208" alt="Screenshot 2021-09-21 at 16 51 55" src="https://user-images.githubusercontent.com/29889908/134207087-b0147b92-d408-4b3f-bd6a-1f4f9877a822.png"><img width="223" alt="Screenshot 2021-09-21 at 16 56 22" src="https://user-images.githubusercontent.com/29889908/134207092-8c9ed092-7069-4b7e-ba56-bfc9ef6c59ac.png">

<img width="213" alt="Screenshot 2021-09-21 at 16 56 35" src="https://user-images.githubusercontent.com/29889908/134207234-36465c3d-f677-464c-a601-606147094441.png"><img width="222" alt="Screenshot 2021-09-21 at 16 56 45" src="https://user-images.githubusercontent.com/29889908/134207235-f8d0fc17-921c-406d-a30b-0064cc742a66.png">

## Before vs After in legacy mode
<img width="208" alt="Screenshot 2021-09-21 at 17 15 17" src="https://user-images.githubusercontent.com/29889908/134208027-857cd4de-fb6b-4f1a-af69-3cc0e261a619.png"><img width="224" alt="Screenshot 2021-09-21 at 17 15 25" src="https://user-images.githubusercontent.com/29889908/134208029-7d498b7f-7746-4b96-a80f-fc0b78548afb.png">

<img width="205" alt="Screenshot 2021-09-21 at 17 15 35" src="https://user-images.githubusercontent.com/29889908/134208031-64289bb3-f14c-41ee-a23a-f619185b063a.png"><img width="223" alt="Screenshot 2021-09-21 at 17 15 43" src="https://user-images.githubusercontent.com/29889908/134208034-e7921288-2845-423f-b558-f933130d3e91.png">

## Before vs After of `vertical-align: top` on `<sup>`
Worth noting that some sections in the full page example use the `<sup>` tag within the summary line, which pushes things out of alignment. Don't think this is something for us to fix, but users may want to use `vertical-align: top` to stop things being pushed out of alignment.

<img width="223" alt="Screenshot 2021-09-21 at 16 57 01" src="https://user-images.githubusercontent.com/29889908/134207528-e62843f3-0680-49e8-9b0b-7f4212462ab0.png"><img width="224" alt="Screenshot 2021-09-21 at 17 13 16" src="https://user-images.githubusercontent.com/29889908/134207646-5698ab98-c71e-4a93-9135-e3483ece9b81.png">

**Comment by vanitabarrett** [comment]
Note: changes still need to be made and pushed to the accordion branch before this ticket can be closed.

**Comment by vanitabarrett** [comment]
Fix pushed to https://github.com/alphagov/govuk-frontend/pull/2257/commits/2f2fc58f49d2697c66fab5e79ae543b7767ddd38 for testing

**Comment by hannalaakso** [comment]
@vanitabarrett Great investigation, this seems to have fixed the issue 🎉  Tested this on Galaxy S21 on Chrome, FF and Samsung Internet.
