### ISSUE TITLE
Accordion focus state summary on desktop has a gap between lines when it wraps

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2371]
## What

@christopherthomasdesign noticed that in the desktop version (tested in Chrome so far) of the new accordion summary, the lines of the summary don't wrap tightly and leave a gap and a visible black line in-between (unlike the above heading focus state which renders the focus state correctly):

![Screenshot 2021-09-29 at 14 20 02](https://user-images.githubusercontent.com/5007934/135276422-64d27228-5b71-4320-84ee-286da5304039.png)

## Why

The focus state for the summary should render consistently at all breakpoints.

It's worth noting though that as we're going to advise teams to either avoid using the summary line or advise them to keep it short, a situation where the summary line wraps on desktop might be less likely.

## Who needs to know about this

Developer, designer

## Done when

- [ ] The focus state for multi-line summary renders consistently on desktop

**Comment by vanitabarrett** [comment]
I don’t fully understand why this is happening, but it looks like it’s related to us setting `govuk-font` and therefore `line-height` on the accordion button element which wraps around the three text elements: heading text, summary line and show/hide. 

It doesn’t look like the text elements are inheriting the line-height from the button - if I inspect the computed line-height value in the dev tools, it comes out as 25px (vs 30px on the button). However, removing the font set on the button and instead setting it on individual text elements seems to resolve the issue. I think doing this might make more sense anyway, as we were essentially using the button class to make all text inside the accordion styled like a heading, and then overriding that later on in the CSS.

The only issue I found in doing this is that the spacing between each text element becomes slightly smaller. We can increase the margin-top defined in the pseudo elements to counteract this a bit.

## Screenshots with the above fix (desktop)
Also checked on mobile to make sure the focus state is unaffected.

### Chrome
<img width="50%" alt="Screenshot 2021-09-30 at 15 33 12" src="https://user-images.githubusercontent.com/29889908/135479273-27df7a4f-530e-4a9d-b222-92d42f70dead.png"><img width="50%" alt="Screenshot 2021-09-30 at 15 33 26" src="https://user-images.githubusercontent.com/29889908/135479280-c51d2c3f-2fcc-41b4-9175-fc2ec3d8168f.png">

### Firefox
<img width="50%" alt="Screenshot 2021-09-30 at 15 34 38" src="https://user-images.githubusercontent.com/29889908/135479211-24408825-173c-4625-9d00-a329f84c2a7d.png"><img width="50%" alt="Screenshot 2021-09-30 at 15 34 51" src="https://user-images.githubusercontent.com/29889908/135479218-a6fe7e5d-7965-4de0-a438-bbfbf9a411d6.png">

### Safari
<img width="50%" alt="Screenshot 2021-09-30 at 15 37 14" src="https://user-images.githubusercontent.com/29889908/135479128-3077ec0d-2a60-42e5-a70d-5db6006efb6d.png"><img width="50%" alt="Screenshot 2021-09-30 at 15 37 27" src="https://user-images.githubusercontent.com/29889908/135479136-5eb54686-9c1c-48c1-853b-6acf1e3292f6.png">

### IE9
<img width="50%" alt="Screenshot 2021-09-30 at 15 43 48" src="https://user-images.githubusercontent.com/29889908/135479041-1ef28378-c534-4e62-b8a7-e0fc005246c9.png"><img width="50%" alt="Screenshot 2021-09-30 at 15 43 58" src="https://user-images.githubusercontent.com/29889908/135479050-07e03079-801e-4b18-a608-6f9aaedc1991.png">

### IE10
<img width="50%" alt="Screenshot 2021-09-30 at 15 45 16" src="https://user-images.githubusercontent.com/29889908/135478599-803bd4b4-7663-4440-9d5c-bddcb8cdd00c.png"><img 
width="50%" alt="Screenshot 2021-09-30 at 15 45 27" src="https://user-images.githubusercontent.com/29889908/135478611-2e9dff7e-6936-4c26-8b75-b56873e09161.png">

**Comment by vanitabarrett** [comment]
@hannalaakso has quite rightly pointed out that `govuk-font` on the accordion heading was originally added to resolve [an issue where legacy code affects the accordion height](https://github.com/alphagov/govuk-frontend/issues/1789), and so the change linked to above might have an impact on the height of the component.

I tested the change (without any changes to the pseudo element `margin-top` to see how much moving the `govuk-font` definition affects the height of the accordion.

**Accordion height:**
Current (legacy mode): 142
New version (legacy mode): 136.234

Current: 142.766
New version: 137.766

![Old and New (no pseudo element change)](https://user-images.githubusercontent.com/29889908/135608247-e34dc187-fd2a-4ee5-9775-c5e1efee5ab2.png)

This shows that removing the `govuk-font` definition on the section heading and button, and moving it to the heading focus wrapper reduces the height (and therefore the touch area) of the accordion because primarily the summary line and show/hide button shift upwards.

This change is probably expected as we’re changing the line height of the text elements. 

However, we can adjust the `margin-top` set on the pseudo elements, which adds additional spacing above the summary line and show/hide.

**Accordion height with 13px margin-top on pseudo elements:**

Current (legacy mode): 142
New (legacy mode): 142.234

Current: 142.766
New: 143.766

Current (mobile legacy): 157.953
New (mobile legacy): 160

Current (mobile): 160.984
New (mobile): 163.984

![Old and new with 13px](https://user-images.githubusercontent.com/29889908/135608468-af64dd34-4b12-4216-b748-d6b5c27d3a0f.png)
