### ISSUE TITLE
Spike adjustments to typography scale

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2418]
## What
Spike some adjustments to the typography scale to assess what the changes would look like (and any knock-on effects) and to get an idea of the impact on users.

We want to spike:

- making the `govuk-body` class 19px across breakpoints. We need to think about how this impacts any `govuk-heading` classes as we could end up in a situation where heading text is smaller than body text on mobile
- making the `govuk-body-s` class 16px across breakpoints
- possibly deprecating `govuk-body-xs`
- making a decision on 24px vs 27px (we think we should remove 27px, but it's used in a heading caption - need to check if it's used anywhere else)

## Why
Some of the font-sizes and associated classes in the Design System have been carried over from GOV.UK Elements and probably haven't been revisited for a while. There are some inconsistencies (e.g: 24px and 27px - maybe we should decide on one?) and also some font sizes which we may not recommend using any more (anything below 16px) for accessibility and readability reasons.

Image showing font size and line height at different breakpoints: 
<img width="503" alt="screenshot_2021-11-03_at_09 42 10" src="https://user-images.githubusercontent.com/29889908/140073937-4e64632d-8ee2-49c0-9991-5d5bdad167ac.png">

## Who needs to work on this
Designer; Developer
@christopherthomasdesign and @vanitabarrett were involved in the original discussions with GOV.UK (Mia and Nikin)

## Done when

- [x] Created a branch with the changes above
- [x] We have a better idea of the impact of these changes on our components and typography scales
- [ ] We have a pre-release we can share with GOV.UK for their own testing
- [x] We have decided next steps

**Comment by christopherthomasdesign** [comment]
I asked the community to share their thoughts on Slack. Here's a summary of the comments:
* Some said that because most users hold their phones closer to their face, the smaller text _appears_ larger
* A couple of people tested this quickly for themselves and said when viewing on a phone at their normal reading distance, the 16px text is perceptually bigger than the same text in 19px on a desktop screen further away
* However, others flagged that there may be a greater need for larger text because people often use mobiles on the move, or when doing something else at the same time
* One person noted that anecdotally they've seen that lots of people tend to increase the system-wide font size on their phones – there was also speculation that the trend towards bigger phones means there's less of a need for smaller fonts
* Two well-designed accessible sites (Scope and RNIB) both use the same large font size regardless of mobile or desktop
* In terms of impact on services, the main concern was with tables – it could affect their layout, scannability, or how much data you can fit on the screen

**Comment by christopherthomasdesign** [comment]
A bit of exploration into `govuk-xs` to see why it was included and how it’s used now.

It was a consolidated from Frontend Toolkit when the Design System was created (the Frontend Toolkit included [a 14px/12px mixin](https://github.com/alphagov/govuk_frontend_toolkit/blob/e46f38ebdeef063c601e40580a93e0f5cb8a20aa/stylesheets/_typography.scss#L106-L111)). We did this to make it easy to migrate from the old stuff, and not to clash with any existing designs.

I haven’t found loads of examples of where teams have used the 14px/12px size – one example is the ‘Popular on GOV.UK’ text that was on the [old GOV.UK homepage](https://web.archive.org/web/20150331045536/https://www.gov.uk/).

From searching GitHub for `govuk-xs`, I’ve found it’s mainly used in old prototypes and demos. However, there are some repos that appear to be live services.

In the more relevant repos, it tends to be used for:
* small labels with metadata – for example ‘PDF, 1000KB, 100 pages’, or ‘Last updated: Mon Mar 09 2020 13:36:22’
* tabular data
* confirming an action – for example ‘Changes saved’

It also pops up a lot in adapted copies of GOV.UK Frontend – i.e. other organisations’ websites, services and design systems.

**Comment by owenatgov** [comment]
We're closing this issue in favour of putting together a broader epic to update the font scale which we will work on in the run up to 5.0. Summary of findings from this spike:

- 14 on the font scale is a carryover from Frontend Toolkit. We hypothesise that it made sense at the time to use this font size for certain smaller elements but with the change in screen sizes since then, we are confident in removing it.
- The use of 14 as a primary font size isn't wide spread and we don't believe that there is a legitimate use for it. See Chris's comment above for more details https://github.com/alphagov/govuk-frontend/issues/2418#issuecomment-964079947
- Whilst the use of 14 isn't wide spread, 16 is much more common. We'll need to provide detailed comms so that teams, including us, have time to audit their components which use 16 and the impact of the font not moving from 16 to 14 on mobile.
- This work can be tied into a general review of our font scale. This includes aligning our "t-shirt" size classes eg: `govuk-body-s` across all our different typography styles so that `xs` becomes 16 on the font scale and every proceeding t-shirt size up lines up with it's associated font scale size up eg: s maps to 16, m maps to 19 etc.
