### ISSUE TITLE
Add thousands comma-seperation in character count messages

### ISSUE THREAD

**Issue by dalepotter** [alphagov/govuk-frontend#2568]
## Related component
[Character count](https://design-system.service.gov.uk/components/character-count/)

## Context

The current [GDS content style guide](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#numbers) states:
> For numerals over 999 - insert a comma for clarity: 9,000

...however the information/error message (when over 999 characters) does not include comma separation.  

Example entering 1200 characters in the Design System [documentation page](https://design-system.service.gov.uk/components/character-count/):
![image](https://user-images.githubusercontent.com/8247168/157439409-3b52b7ba-c2e3-44d1-a1b2-f1a190eaae7d.png)

The expected message in this case would be`You have 1,000 characters too many`

## Alternatives

None found yet, but we are considering adding some custom JS to our service. This would modify the comma-seperation message output for screens which use Character Count component.

**Comment by domoscargin** [comment]
Hi @dalepotter,

Thanks for this!

We recommend you use [maximum word count](https://design-system.service.gov.uk/components/character-count/#consider-if-a-word-count-is-more-helpful) for longer answers which might help here.

We think it's a sensible change to consider, since there will be cases where somebody's copying and pasting, or there's just no other way to ask the question. But generally, if there's a situation where a user could enter that many characters/words over the limit, there's probably a different way to design the question.

**Comment by 36degrees** [comment]
We intend to look at this when we pick up the other localisation issues for the character count component.

**Comment by kellylee-gds** [comment]
@querkmachine can you write a summary of work done so far, then update the done whens on this to reflect what we'll need to do next when we pick the other internationalisation work. Thanks!

**Comment by vanitabarrett** [comment]
Another alternative (if there's nothing left to do on this other than release i18n) could be to attach this to a Github milestone and move the card to Ready To Release. I think it'll sit there for a while, but that might be ok?

**Comment by querkmachine** [comment]
Formatting of the character count text has been included in the [internationalisation PR](https://github.com/alphagov/govuk-frontend/pull/2614) as a progressive enhancement for browsers that support Intl.NumberFormat.

**Comment by querkmachine** [comment]
Moving this back to blocked whilst we do internationalisation pre-release testing.

**Comment by 36degrees** [comment]
In the spike [we formatted the number only if it matched the key `count`](https://github.com/alphagov/govuk-frontend/pull/2614/files#diff-cde937e9880b3f4528adf0fe09930dfdb170736d3cb092d42173c11c00995caaR87-R91), but I wonder if it might make sense to format any placeholder replacement that is of type number, rather than tying it specifically to `count`.

**Comment by querkmachine** [comment]
Reopened as was closed in error. The underlying functionality needed for this to work has been completed, but the actual changes to the character count component will happen as part of #2701 and #2805.
