### ISSUE TITLE
Is there a common use case for the `type` option on Button macro?

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#2684]
I was looking through the nunjucks options for Button, and was confused what `type` is for. The docs say:

>Type of input or button – button, submit or reset. Defaults to submit. This has no effect on a elements.

Is there a common use case for this option? I don't think we would suggest anyone uses `reset`, not sure why you'd need to set it to `button`, and if there's a niche case, you could use `attributes`

**Comment by querkmachine** [comment]
Setting `type` to `button` is frequently done when creating a button that uses JavaScript to provide functionality, rather than submitting a form, such as on our own example cookie banner component.

Although not used an awful lot in the design system/Frontend, it's a fairly small quality of life tweak, and I think it's probably used enough by service teams to warrant existing.

**Comment by joelanman** [comment]
thanks for explaining!
