### ISSUE TITLE
Improve and simplify Gulp

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2717]
## What
Simplify our use of Gulp by reducing its use to task running. Write our own scripts for the actual tasks, which do not rely on Gulp.

## Why
Our gulp tasks are complicated and doing too many things: #2243

Additionally, we cannot update a lot of dependencies because of our reliance on `oldie`: #2469 

We had previously [made the decision to move away from Gulp](https://github.com/alphagov/govuk-frontend/issues/2558) and write our own build scripts.

We essentially removed all Gulp usage, then changed our mind with some exceptions

### Composed build tasks can use Gulp

1. Build targets in `tasks/build/**` for **./dist** and **./package**
2. Review app builds in `app/tasks/build/**` for **./app/dist**

But since every Gulp task such as `npx gulp build:package` has a corresponding `npm run build:package` we chose not to document these in [tasks.md](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/tasks.md#gulp-tasks)

### Composed build tasks need logging

But then we realised we lost logging in the terminal so brought some Gulp usage back:

* Limiting `gulp.parallel()` and `gulp.series()` for composed build tasks only
* Limiting `gulp.task()` usage to **gulpfile.mjs** configs only

### Shared tasks without Gulp

But last of all, we split out all the Review app tasks in https://github.com/alphagov/govuk-frontend/pull/3384 which gave us the opportunity to make all shared tasks work without Gulp. We switched to the [export your tasks](https://gulpjs.com/docs/en/getting-started/creating-tasks) pattern vs [using `gulp.task()`](https://gulpjs.com/docs/en/api/task/)

>**Reminder:** This API isn't the recommended pattern anymore - [export your tasks](https://gulpjs.com/docs/en/getting-started/creating-tasks).

All our new tasks are now plain async functions:

```mjs
await files.copy('**/*', {
  srcPath: join(paths.src, 'govuk/assets'),
  destPath: join(paths.app, 'dist/assets')
})
```

Yet they can still be composed into tasks for Gulp's `gulp.series()` and `gulp.parallel()` etc

```mjs
task.name('copy:assets', () => files.copy('**/*', {
  srcPath: join(paths.src, 'govuk/assets'),
  destPath: join(paths.app, 'dist/assets')
}))
```

## Who needs to work on this
Developers

## Who needs to review this
Developers

## Done when

- #2708 
- #2709 
- #2715
- #2714
- #2779 
- #2710 
- #2711 
- #2712 
- #2713
- #2768 
- #2707 
- #2716 
- #2772

**Comment by domoscargin** [comment]
@colinrotherham 

Is there any undocumented work which might be outstanding here? Or should we go ahead and close this sucker?

**Comment by colinrotherham** [comment]
@domoscargin I think we're still missing those lost edits that captured why we're keeping Gulp

We essentially removed all Gulp usage, then changed our mind with some exceptions

## Composed build tasks can use Gulp

1. Build targets in `tasks/build/**` for **./dist** and **./package**
2. Review app builds in `app/tasks/build/**` for **./app/dist**

But since every Gulp task such as `npx gulp build:package` has a corresponding `npm run build:package` we chose not to document these in [tasks.md](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/tasks.md#gulp-tasks)

## Composed build tasks need logging

But then we realised we lost logging in the terminal so brought some Gulp usage back:

* Limiting `gulp.parallel()` and `gulp.series()` for composed build tasks only
* Limiting `gulp.task()` usage to **gulpfile.mjs** configs only

## Shared tasks without Gulp

But last of all, we split out all the Review app tasks in https://github.com/alphagov/govuk-frontend/pull/3384 which gave us the opportunity to make all shared tasks work without Gulp. We switched to the [export your tasks](https://gulpjs.com/docs/en/getting-started/creating-tasks) pattern vs [using `gulp.task()`](https://gulpjs.com/docs/en/api/task/)

>**Reminder:** This API isn't the recommended pattern anymore - [export your tasks](https://gulpjs.com/docs/en/getting-started/creating-tasks).

All our new tasks are now plain async functions:

```mjs
await files.copy('**/*', {
  srcPath: join(paths.src, 'govuk/assets'),
  destPath: join(paths.app, 'dist/assets')
})
```

Yet they can still be composed into tasks for Gulp's `gulp.series()` and `gulp.parallel()` etc

```mjs
task.name('copy:assets', () => files.copy('**/*', {
  srcPath: join(paths.src, 'govuk/assets'),
  destPath: join(paths.app, 'dist/assets')
}))
```

**Comment by domoscargin** [comment]
I've updated the description to reflect the changes to our approach.

And with that, I'm going to call this one done!
