### ISSUE TITLE
Review the text decoration offset for links

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2743]
## What

Revisit the default value for the text decoration offset on links, set by `$govuk-link-underline-offset`:

https://github.com/alphagov/govuk-frontend/blob/c9d331c2a155de6244c8fb240c22923e074a8099/src/govuk/settings/_links.scss#L39-L46

## Why

As noted in https://github.com/alphagov/govuk-frontend/pull/2183#issuecomment-831933308, when we introduced the new link styles we had to make a compromise on the offset of the underlines, as Chromium-based browsers measured the offset differently to other browsers, putting the underline further away.

This issue appears to have been fixed as of Chrome 104 (https://bugs.chromium.org/p/chromium/issues/detail?id=1251634). Once Chrome 104 reaches widespread adoption, we can revisit the value now that the behaviour in different browsers is consistent.

## Who needs to work on this

Designer

## Who needs to review this

Designer and developer?

## Done when

- [ ] Chrome 104 has decent adoption
- [ ] We've reviewed the default value for the underline offset (`$govuk-link-underline-offset`) and made any changes
- [ ] We've checked we're happy with the appearance in all supported browsers

**Comment by 36degrees** [comment]
Changes to links in Chrome 104:

https://user-images.githubusercontent.com/121939/182565784-ced5f6f7-16cc-45d8-9774-7ee303c3100b.mov

**Comment by colinrotherham** [comment]
Just tagging @christopherthomasdesign on this issue as it might be a good time to look at this again

### Background

We think Chrome v104 (August 2022) lifted link underlines 1-2px higher than before, but we only confirmed this when our [**Percy** visual regression](https://percy.io) tests upgraded from Chrome v98 to Chrome v108

### Decimal places

We've nearly finished our switch from Node Sass (deprecated) to Dart Sass (latest) to generate CSS. This means we're now seeing `line-height` calculated to 10 decimal places like ~`line-height: 1.31579`~ `line-height: 1.3157894737`

In a good way, we're now seeing the same styles as other service teams that already switched to Dart Sass

But strangely this has affected link underlines too (GIF showing before/after):

<img src="https://user-images.githubusercontent.com/415517/220889837-d29ec0bd-1b61-4dd4-9331-2eb961149ded.gif" alt="Dart Sass diff example 1" width="75%">

☝️ **Note:** With 10 decimal places we strangely lose the underline breaks for descenders

**Comment by colinrotherham** [comment]
Some screenshots for reference

## Safari 16.3, macOS
<img width="407" alt="Link, Safari 16 3 (macOS)" src="https://user-images.githubusercontent.com/415517/221926753-b2c21f45-afc8-4d81-b7f5-e96b841a2469.png">

## Chrome 110, macOS
<img width="523" alt="Link, Chrome 110 (macOS)" src="https://user-images.githubusercontent.com/415517/221926765-9ce73810-4491-4810-ab0b-03604fd0b6c4.png">

## Firefox 110, macOS
<img width="440" alt="Link, Firefox 110 (macOS)" src="https://user-images.githubusercontent.com/415517/221926769-78c23f1d-7a0c-468f-b82e-35d31c90aec1.png">

## Edge 110, Windows
<img width="407" alt="Link, Edge 110 (Windows)" src="https://user-images.githubusercontent.com/415517/221926774-6b0a6d17-a2e7-4ce1-b164-ff3be4370a06.png">

**Comment by christopherthomasdesign** [comment]
Have done some exploration into this now.

I asked the GDS design community to give feedback on a couple of options. It's worth noting that I've gone on the assumption that it's best for the underline offset to be set at a whole number of pixels away (rather than half pixels). I think this should result in more consistent rendering across different devices – let me know if this is wrong.

The consensus was that for 19px body copy, an equivalent of a 3px underline offset looks better than 2px. This is because the underline interferes less with the overall shape of the text, which should be better for readability. 

It does means that on Chrome the descenders can slightly bump into the line because it doesn't do ink skipping at that distance:

<img width="690" alt="3px chrome" src="https://user-images.githubusercontent.com/19834460/223183873-87ada00f-483f-484c-ac49-563ff9649adf.png">

But we decided the benefits to readability (from the line being further away) outweighed that.

When I was playing around with this in Frontend, I changed the value to `$govuk-link-underline-offset: .1578em !default;` which should calculate to 3px offset when used with 19px text. There's probably a cleverer way to calculate this number in the code, you'll need to help me with that 😅 

I'm not sure if we want to apply this value to links at all sizes in the scale. I had a look at it in the frontend review app in different browsers, and thought it looked fine at all the sizes. I think we currently just have one value that calculates the offset for all type sizes, rather than setting a different one for each size in the scale. I'm fine with the value being optimised for body text, as most links will appear at that size. But interested to hear what others think.
