### ISSUE TITLE
Bind polyfill still needed? It has been flagged as 'exposed dangerous method or function'

### ISSUE THREAD

**Issue by paulmsmith** [alphagov/govuk-frontend#2751]
Developers in my service team have informed me the ['bind' polyfill](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/vendor/polyfills/Function/prototype/bind.mjs) has been flagged in some automated security/threat testing as [Common Weakness Enumeration 749](https://cwe.mitre.org/data/definitions/749.html) because of [line 125](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/vendor/polyfills/Function/prototype/bind.mjs#L125).

```js
bound = Function('binder', 'return function (' + boundArgs.join(',') + '){ return binder.apply(this, arguments); }')(binder);
```

We think it is upset because that bit of code is effectively an inline 'eval' which _technically_ could be used as part of a cross-site scripting exploit.

I thought it might be worth adding this issue to help others.  

I wonder if the polyfill is still needed actually? [CanIUse](https://caniuse.com/mdn-javascript_builtins_function_bind) suggests to me that this polyfill is for IE6 - IE8 and I think the GOVUK Design System team are now working to drop support for IE8?

**Comment by querkmachine** [comment]
Hi @paulmsmith,

You're correct that this is a polyfill for IE8, which we still support in GOV.UK Frontend. We're still at least a couple of months out from dropping support for it completely, but it will eventually be removed as part of #2506.

The polyfill we use is derived from Polyfill.io. [Their version of the code is here](https://github.com/Financial-Times/polyfill-library/blob/8e8af1c9a571fc5ef7e2cf33073c861251da79d0/polyfills/Function/prototype/bind/polyfill.js), though they have since removed support for IE8 and this polyfill with it, so it's unlikely that they will respond to a security report. 

Although it being flagged as a security issue isn't great, this code will only be executed by IE8 and similarly old browsers outside of our support remit, which feels like it mitigates the risk of a serious or widespread security threat. 

I've added this to our [list of known validation warnings](https://github.com/alphagov/govuk-frontend/issues/1280) for now, but I don't think it's likely we'll fix this before we remove polyfills anyway.
