### ISSUE TITLE
Fix hover styling for expanded Exit this Page button

### ISSUE THREAD

**Issue by davidc-gds** [alphagov/govuk-frontend#3246]
## What
When the Exit this Page button is present on a page and the shift key is pressed once or twice, the button expands vertically to show indicators for how many times shift has been pressed.

When the Exit this Page button is expanded and `:hover` happens, the hover styling looks like it doesn't quite reach the centre area of the button.

Shift indicator with `:focus`: 
![image](https://user-images.githubusercontent.com/98318778/216607338-9a2c9113-b2f6-45af-8b2d-ceb77fe04589.png)

Shift indicator with `:hover`:
![image](https://user-images.githubusercontent.com/98318778/216607751-84c58e4f-897f-41ed-aebc-389e3ee99c33.png)

Shift indicator with `:focus` and `:hover`:
![image](https://user-images.githubusercontent.com/98318778/216607431-c452d953-1fd0-4d58-9091-de1d715a46ed.png)

Live prototype where this can be tested, as of 3 February 2023: https://govuk-frontend-pr-3221.herokuapp.com/full-page-examples/child-maintenance

## Why

This is likely a bug due to the fact that buttons aren't generally expected to have extra height, unless inline content is being flowed to multiple lines. In this case the shift-press indicator isn't technically inline content, so the default button hover styling doesn't compensate for this scenario.

We should fix this broadly on the general button styles so that:
- Desktop users who press shift and then hover their pointer over the Exit this Page button don't see styling weirdness
- Future button implementations where a button contains non-text non-inline content don't encounter the same hover state styling issue

## Who needs to work on this
Developer(s)
Accessibility specialist

## Who needs to review this
Exit this Page epic lead, Accessibility specialist

## Done when

- [x] The Exit this Page hover styling looks correct when the shift keypress indicator is visible
- [ ] The implementation has been tested to ensure it doesn't negatively affect existing button styles
- [ ] The implementation is incorporated into our Exit this Page prototype

**Comment by querkmachine** [comment]
This was a pretty simple fix—basically just required removing the explicit background-color style on the indicator container that was a layover from previous iterations. 

While I was there, I noticed that the indicators were also set to always be in white. We normally invert white text to be black when the button is focused to maintain contrast, and it seemed sensible to do the same for the indicators. 

I've changed the indicators to have their colours be defined by `inherit` and `currentcolor` keywords rather than explicit colours, so they follow any colour changes we apply to the button text. The exception is IE8, which doesn't support `currentcolor`, and instead always uses white.

`:focus`
<img width="172" alt="Screenshot 2023-02-03 at 13 55 30" src="https://user-images.githubusercontent.com/1253214/216621148-f202627e-b057-484f-97ab-6538e9dba085.png">

`:hover`
<img width="163" alt="image" src="https://user-images.githubusercontent.com/1253214/216621411-53223eb9-eab1-4ccd-b448-b4d2bca609af.png">

`:focus` and `:hover` 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/1253214/216621473-9114dad8-b613-4490-a0bc-8fb2dfcf4bf6.png">

**Comment by davidc-gds** [comment]
Those 3 screenshots look splendid to me! Do we need anyone else to review, or can this just be implemented and wrapped up?

**Comment by querkmachine** [comment]
@davidc-gds 

@36degrees has noted on the PR that our current method of lighting the indicators doesn't work in forced colour modes. It's not a new problem introduced by this change, nor strictly related to this issue, but it's something we should fix. Happy to do it as part of this or as a separate item if there's a preference one way or the other.

**Comment by davidc-gds** [comment]
Hey @querkmachine I don't have a preference one way or another, though the correct thing would likely be to add another GitHub issue, so that we can search/find it later for reference
