### ISSUE TITLE
Upgrade Rollup

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3462]
## What

Upgrade Rollup and any other related dependencies to the latest version(s).

## Why

We previously pinned Rollup to maintain support for IE8. As [we're dropping support for IE8](#2621), we can unpin the dependency and use the latest version.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Rollup has been upgraded to its latest version

**Comment by colinrotherham** [comment]
Successfully closed by Dependabot (with a little helping hand)

* https://github.com/alphagov/govuk-frontend/pull/3591

> We should go back and simplify the `compileJavaScript` function in `tasks/scripts.mjs` as part of this work – see [#3386 (comment)](https://github.com/alphagov/govuk-frontend/pull/3386#discussion_r1155949622) for details

☝️ Regarding this bit above we sadly couldn't use `{ preserveModules }` whilst we still build UMD bundles, presumably due to the way it uses a factory function to add window globals etc

It'll become dead code once we ship ESM-only (or alongside CommonJS for compatibility) so can be removed later
