### ISSUE TITLE
Remove the JavaScript for the Details component

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3464]
## What 

The JavaScript provides a polyfill for browsers that do not support the `<details>` element natively – in browsers that do support `<details>` it does not do anything.

Ensure that the component is not styled to suggest it can be expanded in browsers that do not natively support the `<details>` element (including IE11, Edge 12-18).

Remove the `data-module` attribute from the HTML in the Nunjucks macro.

Remove the `generateUniqueID` helper function, which is only used by the details polyfill.

## Why

As of GOV.UK Frontend v5.0, JavaScript will only run in browsers that support ES6 modules. The only browser that supports ES6 modules but not the `<details>` element is 'Legacy' Edge (16-18) which does not justify the overhead of including the polyfill.

## Who needs to work on it

Developers

## Who needs to review it

Developers

## Done when

```[tasklist]
- [x] We've looked at browser stats to confirm that 'Legacy' Edge is a small enough part of our visits
- [ ] #3758
- [ ] https://github.com/alphagov/govuk-frontend/issues/3766
```

**Comment by domoscargin** [comment]
Looking at [GOV.UK stats in April/May 2023 (Internal document)](https://docs.google.com/spreadsheets/d/1LxIfOAHOiiV0lpbK8sEiWjinueUjQm03wTfDRTe9mNs/edit#gid=1058926905):

IE11 is roughly around 0.04% of all users and sessions.
Edge 16: 0.0013% of users
Edge 17: 0.0016% of users
Edge 18: 0.0044% of users

Though worth noting that "0.0016% of users" is still 1000+.

**Comment by domoscargin** [comment]
PRs to:

- #3758 
- #3766 

Which would leave only the Dragon issue to look into

**Comment by querkmachine** [comment]
Regarding Dragon specifically, this seems to be an old, old tale. We've reported issues to Nuance about Dragon not supporting basic HTML elements correctly, and they don't seem to care, because ["Dragon is not compatible with web pages and web based services, [they are] not supported!"](https://github.com/alphagov/reported-bugs/issues/35#issuecomment-701498081)

I'm not keen to toss out the functional, semantically correct HTML we already have in order to support something that Nuance refuse to do themselves. It sucks for Dragon users, but it's not so unuseable that it's worth reworking the entire component for all users, IMO. 

We already note in the Design System docs that the component doesn't work with all voice control software (with a link to yet another issue about Dragon). I think that's worth keeping in place for the time being.

**Comment by 36degrees** [comment]
We're going to treat the Dragon issue as separate to this and call this done 🎉
