### ISSUE TITLE
Manually test that v5 works with the Prototype Kit

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3484]
## What

Share our strategy for loading JavaScript to the Prototype Kit team and confirm that  necessary changes on their side are feasible. _Use the change they've made and validate that it works, e.g. build a prototype kit review app._

Add a Prototype Kit example loading the `govuk-frontend` package using [the new Prototype Kit option for loading scripts using `type="module"`](https://github.com/alphagov/govuk-prototype-kit/issues/2078).

The approach discussed on Slack would be to create a new workspace that:
- runs `npx govuk-prototype-kit create dist` to scaffold a new kit
- links the `govuk-frontend` package to use the one in `packages` with `npm link`
- we'd run manually when necessary

Post v5, we can look into added automated tests to check that assets load OK (using Jest + Puppeteer).

## Why

We'll be updating how our JavaScript loads in the browser and need to make sure that our approach is compatible with what the Prototype Kit can support.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] We've implemented a Prototype Kit example that lets us check we integrate OK

**Comment by 36degrees** [comment]
The Prototype Kit team have created [an issue to allow scripts loaded using the plugin system to use `type="module"`](https://github.com/alphagov/govuk-prototype-kit/issues/2078).

**Comment by colinrotherham** [comment]
Just an update to say this issue was no longer blocked so we closed it

The following PRs added support for GOV.UK Frontend v5 as a Prototype Kit plugin:

* https://github.com/alphagov/govuk-prototype-kit/pull/2317
* https://github.com/alphagov/govuk-prototype-kit/pull/2306
* https://github.com/alphagov/govuk-frontend/pull/4101
* https://github.com/alphagov/govuk-frontend/pull/4264

With fixes contributed along the way:

* https://github.com/alphagov/govuk-prototype-kit/pull/2333
* https://github.com/alphagov/govuk-prototype-kit/pull/2349

Two compatibility issues remain but we're tracking these on Slack:

- [ ] Nunjucks templates from GOV.UK Frontend plugin used by internal pages
- [ ] Plugins using GOV.UK Frontend should use `<script defer>` by default
