### ISSUE TITLE
Create the assets for the crown

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#4058]
## What

Create the SVG for the logo used in the header, as well as other applications like the favicon. Relies on us having a clear idea of [where we need to update it](https://github.com/alphagov/govuk-frontend/issues/4057).

```[tasklist]
### Assets shared across v3, v4 and v5.x (Tudor crown)
- [x] Favicon (.ico)(16x16, 32x32, 48x48)
- [x] Apple touch icon (.png) (180x180)
- [x] Mask icon (.svg)
- [x] Open Graph image (.png) (1200x630)
```

```[tasklist]
### v3.x & v4.x assets (Tudor crown)
- [x] Standalone crown (.svg)
- [x] Standalone crown fallback (.png)
- [x] Legacy Apple touch icons (.png) (120x120, 152x152, 167x167)
```

```[tasklist]
### v5.x assets (Tudor crown)
- [x] Logo lockup (.svg)
- [x] Favicon (.svg)
- [x] Android touch icons (.png) (192x192, 512x512)
```

```[tasklist]
### v5.0 transitional assets (St. Edward's crown)
- [x] Logo lockup (.svg)
- [x] Favicon (.svg)
- [x] Android touch icons (.png) (192x192, 512x512)
```

For more info on this list, see notes in https://github.com/alphagov/govuk-frontend/issues/4057#issuecomment-1706617935

## Why

So we can roll out the new crown across GOV.UK.

## Who needs to work on this 

Designer, developer

## Who needs to review this

The crown is already signed off by the Garter and Cabinet Office comms. We'll run versions of the full lockup GOV.‌UK logo by members of the design community and senior people on GOV.UK.

**Comment by colinrotherham** [comment]
Worked with @christopherthomasdesign yesterday to create some new SVG assets

For comparison, a few options:

## Old crown
>File type: SVG with single compound path
>File size: 2,263 bytes

![crown-old](https://github.com/alphagov/govuk-frontend/assets/415517/52114ac2-9369-4af7-9108-c50e215fbdc6)

## New crown
>File type: SVG with single compound path
>File size: 2,423 bytes

![crown-new](https://github.com/alphagov/govuk-frontend/assets/415517/3d77ae64-f47e-4ff1-ad22-08bd3226dc40)

## New crown
>File type: SVG with single compound path
>File size: 2,423 bytes

## New crown, mirrored horizontally
>File type: SVG with single symbol
>File size: 1,511 bytes

But we can be a bit clever and reduce file size since the crown is symmetrical. For the left side we can split it down the middle (half the points), then mirror and transform it for the right

![crown-new-symbol](https://github.com/alphagov/govuk-frontend/assets/415517/3f783509-cd75-460d-b273-0e145d7611cd)

## New crown, mirrored horizontally with one jewel repeated
>File type: SVG with multiple symbols
>File size: 1,486 bytes

Similar to the mirrored example above, we can also move the jewels (circles) to a single repeated symbol

![crown-new-symbol-multi](https://github.com/alphagov/govuk-frontend/assets/415517/6e53ba41-b58e-44dd-8ea2-efffb7b6df77)

**Comment by christopherthomasdesign** [comment]
Update: the design for the full lockup GOV.‌UK logo (including the crown and text) is now complete and has been sent off for trademarking. So this is complete from a visual point of view.

The remaining work is to work out the best SVG implementation, and to apply the new visuals to other places they're needed.

**Comment by christopherthomasdesign** [comment]
Moving to blocked till beeps gets back from holiday and whilst we focus on Design System Day graphics.

**Comment by christopherthomasdesign** [comment]
For future reference, here's a very useful list of assets needed, compiled by @querkmachine: https://docs.google.com/spreadsheets/d/1wG07pVKAgEJLLgW49br5aeK4rAYaq7N4GM2vdro6kfE/edit#gid=0

Will update the task list above to reflect the greater detail on here.

**Comment by christopherthomasdesign** [comment]
Update: assets created and added to team drive, @querkmachine to try implementing using them and see if that uncovers any issues. 

The full logo SVG code may need further refining than what I've been able to do.

Leaving this card open until we've settled on a final set of ready-to-ship assets.

**Comment by querkmachine** [comment]
@christopherthomasdesign @stevenjmesser I've updated the issue to include the transitional assets needed for a potential v5.0 release that maintains use of St. Edward's crown. Thankfully only a couple of new ones needed to accommodate that, as we can reuse many of the existing assets.

**Comment by christopherthomasdesign** [comment]
Have now created and shared the transitional assets, so saying that this one's done 💪
