### ISSUE TITLE
Review content of thrown errors

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4072]
## What

Review the wording of our error message and their names to make sure they're as useful as possible to our users

## Why

The clearer these messages, the easier it will be for users for fix the errors that we raise.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

- [ ] We've gathered all the messages of all errors we'll be throwing in v5
- [ ] We've decided on the wording of the error messages
- [ ] We've implemented any changes necessary in the codebase

**Comment by Vayras** [comment]
@romaricpascal I would like to contribute towards this issue.

**Comment by colinrotherham** [comment]
Just a few per-developer things that have come up across error PRs so far

1. Adding a component name suffix to error messages
1. Explaining _why_ something is wrong (selector, instance type, missed config key)
1. Enclosing variable names in back ticks
1. Enclosing strings in single quotes
1. Enclosing strings in double quotes when they contain single quotes

Most important is to explain why something is wrong, where possible

**Comment by romaricpascal** [comment]
Worth a quick look at how many of our components validate IDs set in `aria-controls` to ensure we're consistent in checking (or not checking) across the board.

**Comment by colinrotherham** [comment]
Another note to say we've begun scoping using CSS selectors

>Checkboxes: [data-module="govuk-checkboxes"] not found

```mjs
throw new ElementError($module, {
  componentName: 'Checkboxes',
  identifier: `[data-module="${Checkboxes.moduleName}"]`
})
```

But others still use `$module`

```
throw new ElementError($module, {
  componentName: 'Exit this page',
  identifier: '$module'
})
```

Either way, do we need to worry when `$module` is overridden making our identifier incorrect?

**Comment by domoscargin** [comment]
Following on from [this doc](https://docs.google.com/document/d/1CIHxeSW7sjUA7GbP01v9xWrANeQeReCw1N5-d8U2dFI/edit#heading=h.6vmoib5b9l5x) and some further discussions, we're aiming to format all our error messages with a mixture of plain English and selectors/variable names in backticks. 

In general, this might look like:

```
<COMPONENT>: <PLAIN_ENGLISH_ELEMENT> (`<ELEMENT_IDENTIFIER>`) [<PLAIN_ENGLISH_ELEMENT_PROPERTY> (`<PROPERTY_IDENTIFIER`)] <ERROR>
```

Where:

**COMPONENT**: Plain English component name (eg: "Character count")
**PLAIN_ENGLISH_ELEMENT**: Plain English element that's causing the issue (eg: "Button")
**ELEMENT_IDENTIFIER**: An identifier for the element in code. It could be a CSS selector, an HTML snippet, or a variable name. Whatever makes the most sense to provide to the end user.
**PLAIN_ENGLISH_ELEMENT_PROPERTY (optional)**:  If the error is caused by a property of the element (such as an attribute), we can include this property in the message.
**PROPERTY_IDENTIFIER (optional)**: An identifier for the property in code. It could be a CSS selector, an HTML snippet, or a variable name. Whatever makes the most sense to provide to the end user.

For example:

```
Checkboxes: Input elements (`<input type="checkbox">`) not found

Header: Button (`.govuk-js-header-toggle`) attribute (`aria-controls`) is not of type string

Character count: Form field (`.govuk-js-character-count`) is not of type `HTMLTextareaElement` or `HTMLInputElement`

Error summary: Root element (`$module`) not found

Tabs: Link elements (`a.govuk-tabs__tab`) not found
```
