### ISSUE TITLE
Restore ability for tests to fail when component initialisation throws

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4103]
## What

Find a way to keep Puppeteer tests failing when they run `initAll` and an error happen on the page.

## Why

We [have set up Jest and Puppeteer to fail if an error happen on the page](https://github.com/alphagov/govuk-frontend/pull/2933). However, recently, [we've updated `initAll` to catch component's initialisation errors](https://github.com/alphagov/govuk-frontend/pull/4067).

A lot of our tests rely on accessing review app pages, which call `initAll`... so won't throw errors and fail tests if one of the components fail to initialise.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] Devise a way to keep tests failing when `initAll` is called and a component throws during initialisation

**Comment by romaricpascal** [comment]
I think it's another symptom of our tests [relying heavily on the review app](https://github.com/alphagov/govuk-frontend/issues/2565). Wondering if the long term fix wouldn't be to move them all to `renderAndInitialise`. Short term, it's probably fine checking for stacktraces in the logs or something similar.

**Comment by colinrotherham** [comment]
Just an update on this as we've hit a snag

Some tests will instantly start to throw errors 😣

For example, **Skip link** errors without an element ID matching the hash fragment

This is because our examples are single-component by design, but we could:

1. Add multi-component previews
2. Add dummy elements to pass the checks
4. Add and document known failures (updating tests accordingly)
5. Prefer `initAll()` unless testing a custom config or `beforeInitialisation()` change
6. Sneakily use different code vs. preview examples like we do for [**Page template** guidance](https://design-system.service.gov.uk/styles/page-template/)

Ideas 1) and 2) impact both the Review app and Design System previews so we should involve a designer

We discussed this at dev catch-up and will leave it on the agenda
