### ISSUE TITLE
checkboxes item conditional -- need a way to force show for validation

### ISSUE THREAD

**Issue by RichardBradley** [alphagov/govuk-frontend#4210]
## Description of the issue

It is a valid GOV.UK ui to have an input inside a checkbox conditional, see "Conditionally revealing a related question" at 
https://design-system.service.gov.uk/components/checkboxes/

If the child input has a validation error, then it is necessary to show it in the UI, even if the parent checkbox is not checked, otherwise users will see an error in the summary but not be able to see the input in question.

... but there is not currently a way to override the "hidden" class on such an input.

For example, if a user does the following:
 * I tick a box that reveals a textarea, e.g. "I cannot X, due to a medical issue"
 * I enter a long description into the "Enter reason(s)" textarea
 * I untick the parent checkbox (perhaps by accident), my long description is hidden
 * I submit the page

Our service then has two main choices:

 a. Discard the user input from the now hidden text area

 b. Display a validation error like "either tick the box or remove your reasons", let the user decide whether they meant to untick the box or not, without losing their data

We would like to do (b), but we can't currently easily un-hide the textarea

## Steps to reproduce the issue

A page template like the following:

```
 <form id="continue-form" method="post">
        {% set reasonPhotoDoesNotMeetGuidlinesHtml %}
            {{ localisedCharacterCount({
                name: "reason-photo-does-not-meet-guidelines",
                id: "reason-photo-does-not-meet-guidelines",
                value: form["reason-photo-does-not-meet-guidelines"] or session.reasonPhotoDoesNotMeetGuidelines,
                label: {
                    text: "enter_reason" | translate
                },
                errorMessage: errors["reason-photo-does-not-meet-guidelines"],
                maxlength: 250,
                threshold: 75,
                isWelshLocale: isWelshLocale
            }) }}
        {% endset %}

        {{ govukCheckboxes({
            idPrefix: "photo-does-not-meet-guidelines",
            name: "photo-does-not-meet-guidelines",
            errorMessage: errors["photo-does-not-meet-guidelines"],
            items: [
                {
                    value: "true",
                    text: "cannot_upload_medical_issue" | translate,
                    checked: form["photo-does-not-meet-guidelines"] or session.reasonPhotoDoesNotMeetGuidelines,
                    conditional: {
                        html: reasonPhotoDoesNotMeetGuidlinesHtml
                    }
                }
            ]
        }) }}
```

(`localisedCharacterCount` above is a wrapped `govukCharacterCount` which contains a `<textarea>`)

When rendering the page with `form["photo-does-not-meet-guidelines"]` set to false and `form["reason-photo-does-not-meet-guidelines"]` containing text and `errors["reason-photo-does-not-meet-guidelines"]` set

## Actual vs expected behaviour

I would expect to be able to instruct the `item` to be non-hidden in the error case, perhaps something like `showIf` below:

```
            items: [
                {
                    value: "true",
                    text: "cannot_upload_medical_issue" | translate,
                    checked: form["photo-does-not-meet-guidelines"] or session.reasonPhotoDoesNotMeetGuidelines,
                    conditional: {
                        html: reasonPhotoDoesNotMeetGuidlinesHtml,
                        showIf: errors["reason-photo-does-not-meet-guidelines"]
                    }
                }
            ]
```

## Environment (where applicable)

- Operating system: all
- Browser: all
- Browser version: all
- GOV.UK Frontend Version:  `4.5.0`

**Comment by RichardBradley** [comment]
I am working around this in the short/medium term by adding a conditional style to the parent checkbox like:

```
            classes: (["reason-child-in-error"] if errors["reason-photo-does-not-meet-guidelines"]),
```

and using CSS like:

```
 .reason-child-in-error .govuk-checkboxes__conditional {
    display: block;
  }
```

**Comment by querkmachine** [comment]
Hi @RichardBradley,

From my perspective, option A is what should happen. I wouldn't personally consider this to be a bug.

Accidentally unchecking a box (and not noticing prior to form submission, especially given it shows/hides a large chunk of the page and ATs will announce it happening) is a much less likely occurrence than it being an intentional decision, such as if the user has opted to change their answer to a different checkbox or combination of checkboxes. In that circumstance, forcing a user to manually delete the contents of a textarea before continuing is unnecessarily burdonesome, and may not be a particularly fast or easy task for some assistive tech users and users with low digital skills.

Consider how this would work on a branching journey without the conditional reveal function. If a user selected a "I cannot X, due to a medical issue" checkbox on page 1, filled out the "Enter reason(s)" textarea on page 2, and then at a future point—such as the review step—went back to change their answer on page 1, would you still direct them to page 2 and ask them to delete their no-longer-relevant answer? I wouldn't think so.

Regardless, in the next few versions of Frontend we're focusing on defining a clear public API for interacting with our components, we can keep the ability to set conditional section visibility without it being tied to the checkbox state in mind for that.

**Comment by RichardBradley** [comment]
You make a good point, thanks

I think when I tested this, I had javascript disabled and the textbox was always visible, and I convinced myself that Option A was incorrectly discarding user input and thus wanted Option B. However, for 99% of users, js will be enabled and unticking the box will hide the textbox, so discarding their input is correct for the reasons you outline.

I'll rethink and see if we can go with Option A

**Comment by querkmachine** [comment]
Hi @RichardBradley

I'm going to close this off based on the discussion we had above. If you think there are any outstanding issues regarding this, feel free to reopen it.
