### ISSUE TITLE
What is the minimum Node version supported by GOV.UK Frontend v5?

### ISSUE THREAD

**Issue by paulrobertlloyd** [alphagov/govuk-frontend#4353]
The `package.json` for `govuk-frontend` suggests it is v4.2.0:

https://github.com/alphagov/govuk-frontend/blob/72c543a0447c15ea61040cf2fbf901005fe1a0c2/packages/govuk-frontend/package.json#L27

This seems unlikely at the best of times given the wondrous world of dependencies in Node, but my suspicion that this is incorrect was further heightened when I spotted that `rollup` v4.1.4 is listed as a dependency, and that [only supports Node versions greater than 18](https://github.com/rollup/rollup/releases/tag/v4.0.0).

Does the `engines.node` value in `package.json` need to be updated, and is v18 (moving to maintenance in the coming days) the correct minimum supported version?

**Comment by colinrotherham** [comment]
Morning @paulrobertlloyd

This came up recently in https://github.com/alphagov/govuk-frontend/pull/3498/commits/60174e1c98ee62c45903e9b8bfa64aac9d7a610f as we're aware that _some_ shipped features need:

* Node.js v12.16.0 for conditional package exports
* Node.js v12.17.0 for ES modules as `*.mjs`
* Node.js v12.17.0 for subpath package exports
* Node.js v12.20.0 for wildcard package exports

But during code review we [discussed it further](https://github.com/alphagov/govuk-frontend/pull/3498/commits/60174e1c98ee62c45903e9b8bfa64aac9d7a610f#r1179450635) and decided a Node.js restriction wasn't necessary (yet)

## Recommendations

That said, we've shipped [package entry points](https://nodejs.org/docs/latest-v18.x/api/packages.html#package-entry-points) since [GOV.UK Frontend v4.1.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.1.0) and fixed ["subpath export" snags](https://github.com/alphagov/govuk-frontend/issues/3755) for both Node.js and tools following Node.js package resolution rules—but these are optional features

Node.js v4.2.0 users _could_ still use our Rollup UMD bundles (CommonJS compatible) so we [currently recommend](https://frontend.design-system.service.gov.uk/installing-with-npm/#requirements):

>If you have not already installed version 4.2.0 or later of Node.js, install the latest Long Term Support (LTS) version.

But will [soon recommend](https://release-5-0--govuk-frontend-docs-preview.netlify.app/installing-with-npm/#requirements):

>GOV.UK Frontend requires Node.js version 12.17.0 or later to support ECMAScript modules. Where possible, we recommend you install the latest Long Term Support (LTS) version.

## Published code

For context, we don't `npm publish` any **package.json** `dependencies` so we're not tied to minimum versions:

1. **Node.js >=18.0.0** for `rollup@^4.1.4`
2. **Node.js >=6.9.0** for `babel@^7.23.2`
3. **Node.js >=14.0.0** for `sass-embedded^1.69.2`
4. **Node.js ^14** for `cssnano@^6.0.1`

i.e. Our published code is already compiled/transpiled/optimised so doesn't need these tools anymore

**Comment by paulrobertlloyd** [comment]
Ah, of course, all things are not what they seem. Thanks so much for the detailed answer, @colinrotherham. Will close this issue.
