### ISSUE TITLE
When using the useTudorCrown: false option this does not apply to all instances of the crown

### ISSUE THREAD

**Issue by gds-jbentham** [alphagov/govuk-frontend#4761]
## Description of the issue

When moving to govuk-frontend  4.8 and using the option `useTudorCrown: false`. 
The crown in the header remains the st edwards crown. However the favicon images are all swapped to the Tudor crown and do not appear to be controlled by the parameter.

If this is something we have missed or the useTudorCrown option needs to be applied more widely let us know

Thanks

## Steps to reproduce the issue

Update to govuk-frontend 4.8 and add
```
    {{ govukHeader({
      homepageUrl: "https://www.gov.uk"
      homepageUrl: "https://www.gov.uk",
      useTudorCrown: false
    }) }}
```
or
```
    {{ govukHeader({
      homepageUrl: "https://www.gov.uk"
      homepageUrl: "https://www.gov.uk"
    }) }}
```

## Actual vs expected behaviour

Actual behaviour:
Favicon is now using the Tudor crown

Expected behaviour:
Favicon is using the st Edwards crown.
The ability to control the roll out of the new crown logo manually within version 4.8

## Environment (where applicable)

- Browser: Chrome
- Browser version: 121.0.6167.160
- GOV.UK Frontend Version: 4.8

**Comment by querkmachine** [comment]
Hi @gds-jbentham,

This is, to some degree, intentional.

The `useTudorCrown` flag is specific to the header component, and only changes what is shown in the header.

Favicons are part of the template. GOV.UK Frontend doesn't really have a simple mechanism for implementing feature flags on the template level. 

Many forks and implementations of Frontend do not use the bundled template, nor directly use the favicons shipped with Frontend (rather, they are copied or processed by build tools in some manner), so adding a flag wouldn't have been guaranteed to work for all users either.

As there is a relatively short period involved (less than a week before the embargo is lifted, as of writing; and only a two week 'transition' after that) replacing the assets _in situ_ was considered preferable to asking developers to rename and re-reference assets in a way that would have to persist for long after the crown transition had completed.

We recognise it's an inconvenience right now, but as there are no other changes involved in 4.8 except for the crown change, hopefully remaining on 4.7 for a teensy bit longer shouldn't be a problem if you need to perform a new release.

**Comment by 36degrees** [comment]
As there is now no reason for team's to continue to use the old crown, and the new crown will become the default in v5.2 I'm going to close this as I don't think there's anything for us to do.
