### ISSUE TITLE
Proposal: Add modifiers to nunjucks templates

### ISSUE THREAD

**Issue by richardTowers** [alphagov/govuk-frontend#667]
At the moment if you want to turn a button into a start button you would use a nunjucks macro like this:

```
{{ govukButton({text: "Start now button", classes: "govuk-button--start"}) }}
<!-- Compiles to -->
<input value="Start now button" type="submit" class="govuk-button govuk-button--start">
```

The macro already knows it's a `govuk-button` element, so it feels redundant having to say it again in the classes. It also means the nunjucks macros don't protect the user from classname changes as well as they might.

What do you think about adding a `modifiers` field alongside `classes` which would automatically prepend the appropriate block / element bits of the classname to the output? So:

```
{{ govukButton({text: "Start now button", modifiers: "start"}) }}
<!-- Compiles to -->
<input value="Start now button" type="submit" class="govuk-button govuk-button--start">
```

**Comment by igloosi** [comment]
Hi @richardTowers 
thanks for raising this.

In the first iteration of the component macros we were using boolean values to represent variants (and output css classes). 

In the base of the button, it can be a `<button>`, `<a>` or `input type="submit"`.  Users might be confused what a modifier does: is it a new class or different tag.

We're open to feedback from users and we'll evaluate this proposal to see if we can make it work for compound components as well, so that the approach is consistent.

**Comment by nickcolley** [comment]
Related: https://github.com/alphagov/govuk-frontend/issues/460

**Comment by richardTowers** [comment]
Ah, I hadn't seen #460, which looks similar enough that I think we should close this one as a dupe.

I'll add another comment to that with my opinions.
