### ISSUE TITLE
Update node version in package.json to allow more recent LTS version

### ISSUE THREAD

**Issue by mike-suggitt** [alphagov/govuk-frontend#734]
Package.json currently locks node version to 8.9.4 but unless there's a very good (and horrible) reason why it needs to limit itself to this can we possibly change it to support latest LTS node version (i.e. node 8.11.2) and greater?

**Comment by nickcolley** [comment]
I've investigated running travis on multiple versions, and it's not too difficult.

Would be good to consider supporting as low LTS as possible, since it may make contribution easier.

We'd still recommend using a specific version otherwise.

See https://github.com/nickcolley/jest-axe/blob/master/.travis.yml for an example.

**Comment by mike-suggitt** [comment]
Hi Ollie,

Thanks for getting back to me. Given that Node 8 is in LTS I would cautiously say that it should be consistent and stable but I understand your concerns. Slightly relaxing the versioning would certainly help third-party teams and developers onboard themselves to your work that much easier as restricting node versions in order to integrate would be a bit of an anti-pattern.

As a workaround I've simply forked the repo and updated the package.json for consumption by latest LTS node then once this repo becomes publicly available we can switch our dependencies across.

Thanks

**Comment by nickcolley** [comment]
@mike-suggitt hey Mike, the minimum requirement for the `govuk-frontend` package is now 4.2.0
https://github.com/alphagov/govuk-frontend/blob/master/package/package.json#L7

If you're looking to contribute you'll need to use [8.9.4](https://github.com/alphagov/govuk-frontend/blob/master/package.json#L5) as otherwise Heroku fails.

We use [nvm](https://github.com/creationix/nvm) to make it easier.

I'm going to close this as I think this addresses your concerns, please re-open if this stops you from using GOV.UK Frontend.
