### ISSUE TITLE
Conditional reveals result in a flash of unstyled content as the page loads

### ISSUE THREAD

**Issue by charge-valtech** [alphagov/govuk-frontend#787]
![fouc-conditional](https://user-images.githubusercontent.com/1433357/41355412-62cb582a-6f19-11e8-8a87-ac2b2bb63261.gif)

As the page loads, the hidden HTML shows briefly before being hidden. This is especially noticeable on slow connections. 

Ideally the hidden area should be hidden by default, and show only once triggered, or if no JS.

**Comment by nickcolley** [comment]
I believe in the development of this feature we managed to avoid depending on the global 'js-enabled' class. This was because we were testing on a page with only the conditional reveal and on a fast connection.

In other components we've had to accept this dependency on a global 'js-enable' class so I think maybe all our components should just follow suit and avoid any issues like this.

**Comment by dankmitchell** [comment]
@nickcolley now that you have fixed this for tabs should we re-open this issue?

**Comment by nickcolley** [comment]
Hey @dankmitchell !

We have added two changes to GOV.UK Frontend to fix conditional reveals and then tabs for this similar issue.

The other issue for tabs is here: https://github.com/alphagov/govuk-frontend/issues/927

So I think both of these are resolved now, is that correct?

**Comment by dankmitchell** [comment]
Ah yes, sorry @nickcolley. I was missing the `govuk-radios__conditional--hidden` class
