### ISSUE TITLE
Question about support for other templating languages 

### ISSUE THREAD

**Issue by davidjamesstone** [alphagov/govuk-frontend#829]
This looks like a good start to better organising the various patterns used across govuk.

I'm a bit confused though about where this leaves some of the other available packages.

We currently use `nodejs` with `hapijs` across our suite of govuk services. Our template of choice is `handlebars`, used via the `govuk_template_mustache` package on npm.

It looks like this `govuk-frontend` is raw html or nunjucks. Does this mean you will only support these going forward, and users need to move to one of these two, or will the `govuk_template_mustache` (+ it's various other package for other template languages) be kept up to date?

Many thanks

**Comment by igloosi** [comment]
Hi @davidjamesstone,
thanks for getting in touch.
GOV.UK Elements, Template and Frontend Toolkit will remain for the time being with basic maintenance support. 

We are considering various options for the template, but I doubt it will be available in the same number of languages.

**Comment by davidjamesstone** [comment]
Thanks @igloosi - it's useful to know the direction.

TBH - I don't have a lot of enthusiasm about `nunjucks`. We have a dozen production govuk services built on the stack outlined above, rewriting them in nunjucks isn't really an option, or desirable.

Anyway - nice start - I'll keep an eye on where it goes & hopefully you'll have support for mustache or similar logic-less templates soon.

Many thanks.

**Comment by 36degrees** [comment]
Hi David,

We’ve written in a little more detail about our [decisions around templating](https://github.com/alphagov/govuk-design-system-architecture/blob/master/decision-records/003-templating-languages.md) in our architecture repo, which I hope might provide some clarity.

We provide the Nunjucks templates because we think that they are useful for users of the Prototype Kit and for teams who are _already_ building production systems using Nunjucks. We are not suggesting or expecting that all teams across government should now be using it. We hope that most departments or teams will build their own abstraction layer (templates or macros for the components they use) in the templating language of their choice.

Hope that helps – I'm going to close this issue for now, but if you have any further questions please do re-open it.

Ollie
