### ISSUE TITLE
Allow the 'Details' component to be used within form components

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#874]
_From @jfranciswebdesign on July 5, 2018 8:34_

## What
> Allow the 'Details' component to be used within form components (for example, radio buttons)
![image](https://user-images.githubusercontent.com/5270013/42311595-201c49b6-8036-11e8-9060-4565c64e0532.png)

## Why
The hint text item is not suitable for large amounts of 'help' content, or content which does not need to be seen by the majority of users.

_Copied from original issue: alphagov/govuk-design-system-backlog#147_

**Comment by nickcolley** [comment]
By using the individual components and composing them this should be possible.

See https://github.com/alphagov/govuk-frontend/blob/master/app/views/examples/form-alignment/index.njk#L52 for an example of this.

I wonder where we could document this...

**Comment by nickcolley** [comment]
```html<form action="/form-handler" method="post">
  {% call govukFieldset({
    legend: {
      text: "How did you prepare your accounts?",
      isPageHeading: true,
      classes: "govuk-fieldset__legend--xl"
    }
  }) %}
    {{ govukDetails({
      summaryText: "What's this?",
      text: "Lorem ipsum"
    }) }}
    {{ govukRadios({
      idPrefix: "how-did-you-prepare-your-accounts",
      name: "how-did-you-prepare-your-accounts",
      items: [
        {
          value: "standard-102",
          text: "These financial statements have been prepared in accordance with the provisions of Section 1A (Small Entities) of Financial Reporting Standard 102"
        },
        {
          value: "other-standard",
          text: "These accounts ahve been prepared in accordance with another standard"
        }
      ]
    }) }}
  {% endcall %}

  {{ govukButton({
    text: "Continue"
  }) }}
</form>
```

**Comment by nickcolley** [comment]
I'm going to close this out, @jfranciswebdesign, feel free to re-open if you need any more help :)

**Comment by jfranciswebdesign** [comment]
This is great - thanks all for the speedy turnaround.

**Comment by Vikingwind** [comment]
Hi, We in Norwegian Labour and Welfare Administration design system has same problem of detail solution for question in form. Because of long and annoying content and description of each question, we need to use detail component, but too many of them will still create much visual noise for user. Any suggestions?
![Skjermbilde 2022-03-03 kl  10 46 20](https://user-images.githubusercontent.com/24367251/156543577-47f98da3-ef1d-484b-b0a3-e5e05846f01d.png)
![Skjermbilde 2022-03-03 kl  10 50 14](https://user-images.githubusercontent.com/24367251/156543603-5fcdbb8a-f199-418f-8989-c2d375b61c4b.png)
