### ISSUE TITLE
Supply layout template for other languages (Rails, Python...)

### ISSUE THREAD

**Issue by axemonkey** [alphagov/govuk-frontend#964]
When implementing the Design System in a Rails app, I am able to include the assets (CSS, JS, fonts, images) easily enough, but the only layout file supplied is `template.njk` so I have to manually create `views/layouts/application.slim` myself, and then it will degrade over time and need to be recreated when the system is updated.

It would be ace to have a `slim` or perhaps just `erb` version of the template for Rails apps.

**Comment by joelanman** [comment]
We've made an initial decision to just support HTML and Nunjucks centrally. However I think this issue is useful for the community to discuss the issue of supporting other languages, for example other teams might want to maintain official ports of the template to other languages.

**Comment by hannalaakso** [comment]
This decision record is also useful context here as it details what was done in alpha and some of the challenges we've identified: https://github.com/alphagov/govuk-design-system-architecture/blob/master/decision-records/003-templating-languages.md

**Comment by andymantell** [comment]
If anyone's looking for a Python solution - I've now got fully working Jinja2 versions of all the govuk-frontend Nunjucks macros. I'm looking to get them published to PyPi but that will take a little bit of time while I jump over various hurdles to get the code published (hopefully not insurmountable, mostly just matters of approval, and sorting out a release process to keep them up to date and tested), but in the meantime just give me a shout and I can help set it up. What I've done is write a script that converts from Nunjucks to Jinja2 (Since they are "similar"). I've popped the script in this Gist:

https://gist.github.com/andymantell/8b1bb037341f38990a4d019894abd83e

The idea is that the Gulp task grabs the files it needs directly from the version of govuk-frontend that is in your `node_modules` directory so the templates will always be in step with the govuk-frontend css/js. It's unlikely to work for anyone exactly as is, but the core of it is fine. You'd need to get it loaded into your Gulp setup, or convert it to something else if you aren't using Gulp. And there are some specific things in there around paths etc that would need adjusting to your situation. (For example, the script assumes that your templates are loaded with jinja's `PrefixLoader` set to `app/`)

Once this is done, you can use the nunjucks examples from the design system pretty much as is, except you will need to quote the keys in the dicts when you invoke the macros.

In addition to this - I am currently working on a set of macros that make it easier to pipe [flask-wtf forms](https://flask-wtf.readthedocs.io/en/stable/) directly into the govuk-frontend macros. Mostly just a case of mapping the pieces of the form object to the correct part of the govuk params.

**All this comes with the caveat that none of this is tested or used in production yet - I'm just getting it set up for teams to use so I can't guarantee that there aren't issues.**

**Comment by leonk** [comment]
@andymantell I’d be interested to know how you get on with this approach. I’m looking at doing a similar thing, but for twig in PHP. Just seeing if it’s a viable option.

Did you look into using https://github.com/shawnbot/meta-template at all to do the file conversion?

**Comment by andymantell** [comment]
Hi @leonk,

The script I've pasted is fully working so in terms of viability I think it's a goer. I'm happy that the templates are working correctly, barring any edge case bugs.

I did look meta-template briefly but the readme file suggested it was quite early days so I didn't pursue it. I proceeded on the assumption that Jinja and Nunjucks were similar enough that a few string replacements would do the trick (true => True, quoting object/dict keys etc). The reality turned out to be a little more painful than I realised, but what I've done still mostly amounts to relatively simple string manipulation. The regular expressions got a bit gnarly, but conceptually the transformations weren't complicated. A lot of the differences (particularly the more annoying ones) were the result of the behaviours of the underlying language. And one that was probably either a bug in Jinja or a bug in Nunjucks, because the GOV.UK Nunjucks implementation just did not work whatever I did (The bit where each component macro simply includes an include, and expects the `params` to still be there)

Given that Twig is inspired by Jinja (And actually written by the same guy) you might well get away with a similar process. Basically I kept adding lines to my script until Python stopped throwing errors.

Give it a go :-)

**Comment by hannalaakso** [comment]
Hi @axemonkey 

Thanks for raising this. 

Our team understand that there's interest in multiple templating language versions of Template. 

I think we asked you to raise this issue with the intention of having the relevant questions asked/resources shared recorded somewhere but on second thought an issue in GOV.UK Frontend is probably not the best place to do this. 

As discussed in our [decision record](https://github.com/alphagov/govuk-design-system-architecture/blob/master/decision-records/003-templating-languages.md) this work is, for various reasons, not something that our team is looking to do at this time.

For that reason we're going to close this issue but the conversations on it have been logged in our backlog. 

We'd definitely like to have a better way of sharing the resources that come from the community (like @andymantell's Jinja port) and the related discussions, but we're not sure what the best format is for this yet – hopefully this is something we'll be able to explore soon.

Thanks again for taking the time to raise the issue and also to others who've commented on this issue.

Hanna

**Comment by hannalaakso** [comment]
Some of the ports made have been collected here: https://github.com/tijmenb/design-system-community-resources
