### ISSUE TITLE
Does link ink skipping cause some users to see single links as multiple links?

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#973]
Does link ink skipping cause some users to see single links as multiple links, and is this a problem?

This issue was raised previously here: https://github.com/alphagov/govuk_template/issues/339

**Comment by markhurrell** [comment]
have we seen any evidence of this causing problems? would hover/active/focus states reduce the chance of it happening?

traditional link underlines obstruct the descenders on letters, which is pretty much the most basic thing you shouldn't do for legibility. I'd want to see significant evidence of ink skipping actually causing users difficulty the justify not having it

**Comment by timpaul** [comment]
Not that I'm aware of. I agree, we'd need evidence of it being an issue on GOV.UK first. Here's an example of where it can cause genuine ambiguity:

![image](https://user-images.githubusercontent.com/1590604/44905271-78ee6380-ad09-11e8-97bf-ba0158151d85.png)

However, we've tested this text with the New Transport font and it doesn't cause the same problem:

![image](https://user-images.githubusercontent.com/1590604/44905335-aaffc580-ad09-11e8-8aeb-30c4d36ce8fa.png)

**Comment by timpaul** [comment]
Closing this now. If we find evidence that it's causing issues we can reopen.

**Comment by Dean-A-Smith** [comment]
Hi. I haven't seen a member of the public have an issue with this, but I have had colleagues outside of digital and design ask me why there are rogue full stops in pieces of content I've worked on. When I go to find out what they mean, I find what they've seen is an end section of a link where the underline has been interrupted by another symbol at the end, leaving just a dot of underline.

![image](https://user-images.githubusercontent.com/49518181/123812063-b1fd1700-d8eb-11eb-8a41-d4a3920a29de.png)

The context here is people in government checking content for accuracy, rather than scanning it or using it for a purpose, but thought it worth sharing.

**Comment by lfdebrux** [comment]
We've now turned off ink skipping in version 3.13.0 of GOV.UK Frontend (see #2251), so this should no longer be an issue.
